#!/usr/bin/env python3
"""Part 2: Add remaining teams to wiki_squads.json"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def P(num, name, cn, pos, poscn, club, clubcn=""):
    return {"number":num,"name":name,"name_cn":cn,"position":pos,"position_cn":poscn,"club":club,"club_cn":clubcn or club}

wiki = json.load(open('wiki_squads.json', encoding='utf-8'))

# ===== GROUP D =====
wiki["USA"] = {"coach":"Mauricio Pochettino","players":[
    P("1","Matt Turner","马特·特纳","Goalkeeper","门将","New England Revolution","新英格兰革命"),
    P("12","Chris Brady","克里斯·布雷迪","Goalkeeper","门将","Chicago Fire","芝加哥火焰"),
    P("23","Matt Freese","马特·弗里兹","Goalkeeper","门将","NYCFC","纽约城"),
    P("2","Sergiño Dest","塞尔吉尼奥·德斯特","Right-Back","右后卫","PSV Eindhoven","PSV埃因霍温"),
    P("3","Antonee Robinson","安东尼·罗宾逊","Left-Back","左后卫","Fulham","富勒姆"),
    P("4","Chris Richards","克里斯·理查兹","Centre-Back","中后卫","Crystal Palace","水晶宫"),
    P("5","Tim Ream","蒂姆·里姆","Centre-Back","中后卫","Charlotte FC","夏洛特FC"),
    P("13","Mark McKenzie","马克·麦肯齐","Centre-Back","中后卫","Toulouse","图卢兹"),
    P("15","Miles Robinson","迈尔斯·罗宾逊","Centre-Back","中后卫","FC Cincinnati","辛辛那提"),
    P("22","Joe Scally","乔·斯卡利","Right-Back","右后卫","Borussia Mönchengladbach","门兴"),
    P("6","Weston McKennie","韦斯顿·麦肯尼","Central Midfield","中前卫","Juventus","尤文图斯"),
    P("7","Tyler Adams","泰勒·亚当斯","Defensive Midfield","防守中场","Bournemouth","伯恩茅斯"),
    P("8","Gio Reyna","乔瓦尼·雷纳","Attacking Midfield","攻击中场","Borussia Mönchengladbach","门兴"),
    P("14","Malik Tillman","马利克·蒂尔曼","Attacking Midfield","攻击中场","Bayer Leverkusen","勒沃库森"),
    P("16","Tim Weah","蒂姆·维阿","Winger","边锋","Marseille","马赛"),
    P("10","Christian Pulisic","克里斯蒂安·普利西奇","Left Wing","左边锋","AC Milan","AC米兰"),
    P("9","Folarin Balogun","福拉林·巴洛贡","Centre-Forward","中锋","AS Monaco","摩纳哥"),
    P("11","Ricardo Pepi","里卡多·佩皮","Centre-Forward","中锋","PSV Eindhoven","PSV埃因霍温"),
    P("17","Haji Wright","哈吉·赖特","Forward","前锋","Coventry City","考文垂"),
    P("18","Alex Zendejas","亚历克斯·森德哈斯","Winger","边锋","Club América","美洲队"),
    P("19","Brenden Aaronson","布伦登·阿伦森","Midfielder","中场","Leeds United","利兹联"),
    P("20","Cristian Roldan","克里斯蒂安·罗尔丹","Midfielder","中场","Seattle Sounders","西雅图海湾人"),
    P("21","Auston Trusty","奥斯顿·特鲁斯蒂","Defender","后卫","Celtic","凯尔特人"),
    P("24","Max Arfsten","马克斯·阿夫斯滕","Defender","后卫","Columbus Crew","哥伦布机员"),
    P("25","Alex Freeman","亚历克斯·弗里曼","Defender","后卫","Villarreal","比利亚雷亚尔"),
    P("26","Sebastian Berhalter","塞巴斯蒂安·贝尔哈特","Midfielder","中场","Vancouver Whitecaps","温哥华白帽"),
]}

wiki["Paraguay"] = {"coach":"Gustavo Alfaro","players":[
    P("1","Roberto Fernández","罗伯托·费尔南德斯","Goalkeeper","门将","Cerro Porteño","波特诺山丘"),
    P("12","Orlando Gill","奥兰多·希尔","Goalkeeper","门将","San Lorenzo","圣洛伦索"),
    P("23","Gastón Olveira","加斯顿·奥尔维拉","Goalkeeper","门将","Olimpia","奥林匹亚"),
    P("2","Gustavo Gómez","古斯塔沃·戈麦斯","Centre-Back","中后卫","Palmeiras","帕尔梅拉斯"),
    P("3","Júnior Alonso","儒尼奥尔·阿隆索","Centre-Back","中后卫","Atlético Mineiro","米内罗竞技"),
    P("4","Fabián Balbuena","法比安·巴尔武埃纳","Centre-Back","中后卫","Grêmio","格雷米奥"),
    P("5","Omar Alderete","奥马尔·阿尔德雷特","Centre-Back","中后卫","Sunderland","桑德兰"),
    P("6","Miguel Almirón","米格尔·阿尔米隆","Attacking Midfield","攻击中场","Atlanta United","亚特兰大联"),
    P("8","Diego Gómez","迭戈·戈麦斯","Central Midfield","中前卫","Brighton","布莱顿"),
    P("14","Ramón Sosa","拉蒙·索萨","Winger","边锋","Palmeiras","帕尔梅拉斯"),
    P("10","Julio Enciso","胡利奥·恩西索","Attacking Midfield","攻击中场","Strasbourg","斯特拉斯堡"),
    P("7","Damián Bobadilla","达米安·博瓦迪利亚","Defensive Midfield","防守中场","São Paulo","圣保罗"),
    P("9","Antonio Sanabria","安东尼奥·萨纳布里亚","Centre-Forward","中锋","Cremonese","克雷莫纳"),
    P("11","Gabriel Ávalos","加布里埃尔·阿瓦洛斯","Centre-Forward","中锋","Independiente","独立"),
    P("15","Alex Arce","亚历克斯·阿尔塞","Forward","前锋","Independiente Rivadavia","独立里瓦达维亚"),
    P("17","Isidro Pitta","伊西德罗·皮塔","Forward","前锋","Red Bull Bragantino","布拉甘蒂诺红牛"),
]}

wiki["Australia"] = {"coach":"Tony Popovic","players":[
    P("1","Mathew Ryan","马修·瑞安","Goalkeeper","门将","Levante","莱万特"),
    P("12","Paul Izzo","保罗·伊佐","Goalkeeper","门将","Randers FC","兰德斯"),
    P("18","Patrick Beach","帕特里克·比奇","Goalkeeper","门将","Melbourne City","墨尔本城"),
    P("2","Harry Souttar","哈里·苏塔尔","Centre-Back","中后卫","Leicester City","莱斯特城"),
    P("3","Cameron Burgess","卡梅隆·伯吉斯","Centre-Back","中后卫","Swansea City","斯旺西城"),
    P("4","Alessandro Circati","亚历山德罗·奇尔卡蒂","Centre-Back","中后卫","Parma","帕尔马"),
    P("5","Milos Degenek","米洛斯·德格内克","Centre-Back","中后卫","APOEL Nicosia","希腊人竞技"),
    P("16","Aziz Behich","阿齐兹·贝希奇","Left-Back","左后卫","Melbourne City","墨尔本城"),
    P("6","Jackson Irvine","杰克逊·欧文","Central Midfield","中前卫","St. Pauli","圣保利"),
    P("8","Connor Metcalfe","康纳·梅特卡夫","Central Midfield","中前卫","St. Pauli","圣保利"),
    P("10","Ajdin Hrustic","艾丁·赫鲁斯蒂奇","Attacking Midfield","攻击中场","Heracles Almelo","赫拉克勒斯"),
    P("7","Mathew Leckie","马修·莱基","Winger","边锋","Melbourne City","墨尔本城"),
    P("9","Nestory Irankunda","内斯托里·伊兰昆达","Winger","边锋","Watford","沃特福德"),
    P("11","Awer Mabil","阿韦尔·马比尔","Winger","边锋","Castellón","卡斯特利翁"),
    P("14","Cristian Volpato","克里斯蒂安·沃尔帕托","Attacking Midfield","攻击中场","Sassuolo","萨索洛"),
    P("15","Mohamed Touré","穆罕默德·图雷","Forward","前锋","Norwich City","诺维奇城"),
    P("17","Nishan Velupillay","尼尚·维卢皮莱","Forward","前锋","Melbourne Victory","墨尔本胜利"),
    P("19","Tete Yengi","特特·延吉","Forward","前锋","Machida Zelvia","町田泽维亚"),
    P("20","Aiden O'Neill","艾登·奥尼尔","Midfielder","中场","NYCFC","纽约城"),
    P("21","Cameron Devlin","卡梅隆·德夫林","Midfielder","中场","Hearts","哈茨"),
]}

wiki["Turkey"] = {"coach":"Vincenzo Montella","players":[
    P("1","Mert Günok","梅尔特·居诺克","Goalkeeper","门将","Beşiktaş","贝西克塔什"),
    P("12","Altay Bayındır","阿尔泰·巴因德尔","Goalkeeper","门将","Manchester United","曼联"),
    P("23","Uğurcan Çakır","乌乌尔詹·恰克尔","Goalkeeper","门将","Trabzonspor","特拉布宗体育"),
    P("2","Zeki Çelik","泽基·切利克","Right-Back","右后卫","Roma","罗马"),
    P("3","Merih Demiral","梅里赫·德米拉尔","Centre-Back","中后卫","Al-Ahli","吉达国民"),
    P("4","Çağlar Söyüncü","恰拉尔·瑟云居","Centre-Back","中后卫","Fenerbahçe","费内巴切"),
    P("5","Abdülkerim Bardakcı","阿卜杜勒克里姆·巴尔达克奇","Centre-Back","中后卫","Galatasaray","加拉塔萨雷"),
    P("6","Orkun Kökçü","奥尔昆·柯克曲","Central Midfield","中前卫","Benfica","本菲卡"),
    P("8","Hakan Çalhanoğlu","哈坎·恰尔汗奥卢","Central Midfield","中前卫","Inter Milan","国际米兰"),
    P("10","Arda Güler","阿尔达·居莱尔","Attacking Midfield","攻击中场","Real Madrid","皇家马德里"),
    P("14","Salih Özcan","萨利赫·厄兹詹","Defensive Midfield","防守中场","Borussia Dortmund","多特蒙德"),
    P("7","Kerem Aktürkoğlu","凯雷姆·阿克蒂尔科卢","Left Wing","左边锋","Galatasaray","加拉塔萨雷"),
    P("9","Barış Alper Yılmaz","巴里什·阿尔珀·耶尔马兹","Forward","前锋","Galatasaray","加拉塔萨雷"),
    P("11","Kenan Yıldız","凯南·耶尔德兹","Forward","前锋","Juventus","尤文图斯"),
    P("17","Bertuğ Yıldırım","贝尔图·耶尔德勒姆","Centre-Forward","中锋","Rennes","雷恩"),
    P("19","Semih Kılıçsoy","塞米赫·克勒奇索伊","Forward","前锋","Beşiktaş","贝西克塔什"),
]}

# ===== GROUP E =====
wiki["Curaçao"] = {"coach":"Dick Advocaat","players":[
    P("1","Eloy Room","埃洛伊·鲁姆","Goalkeeper","门将","Vitesse","维特斯"),
    P("2","Jurich Carolina","尤里奇·卡罗莱纳","Defender","后卫","Miedź Legnica","梅吉莱格尼察"),
    P("3","Cuco Martina","库科·马蒂纳","Defender","后卫","NAC Breda","布雷达"),
    P("4","Roshon van Eijma","罗肖恩·范艾马","Centre-Back","中后卫","RKC Waalwijk","瓦尔韦克"),
    P("5","Nathangelo Markelo","纳坦杰洛·马克洛","Defender","后卫","Fortuna Sittard","锡塔德幸运"),
    P("6","Vurnon Anita","富农·阿尼塔","Defensive Midfield","防守中场","RKC Waalwijk","瓦尔韦克"),
    P("7","Leandro Bacuna","莱安德罗·巴库纳","Central Midfield","中前卫","FC Groningen","格罗宁根"),
    P("8","Godfried Roemeratoe","戈弗雷德·罗梅拉托","Midfielder","中场","Heracles Almelo","赫拉克勒斯"),
    P("9","Rangelo Janga","兰杰洛·扬哈","Centre-Forward","中锋","CFR Cluj","克卢日"),
    P("10","Anthony van den Hurk","安东尼·范登胡尔克","Forward","前锋","Helmond Sport","海尔蒙特体育"),
    P("11","Juninho Bacuna","朱尼尼奥·巴库纳","Attacking Midfield","攻击中场","Birmingham City","伯明翰城"),
    P("12","Kenji Gorré","肯吉·戈雷","Winger","边锋","Boavista","博阿维斯塔"),
    P("13","Jafar Arias","贾法尔·阿里亚斯","Forward","前锋","FC Emmen","埃门"),
    P("14","Jeremy Antonisse","杰雷米·安东尼斯","Winger","边锋","FC Eindhoven","埃因霍温FC"),
    P("15","Richairo Živković","里查伊罗·日夫科维奇","Forward","前锋","Lion City Sailors","狮城水手"),
]}

wiki["Ivory Coast"] = {"coach":"Emerse Faé","players":[
    P("1","Yahia Fofana","亚希亚·福法纳","Goalkeeper","门将","Angers","昂热"),
    P("2","Wilfried Singo","威尔弗里德·辛戈","Right-Back","右后卫","AS Monaco","摩纳哥"),
    P("3","Evan Ndicka","埃文·恩迪卡","Centre-Back","中后卫","Roma","罗马"),
    P("4","Ousmane Diomande","奥斯曼·迪奥曼德","Centre-Back","中后卫","Sporting CP","葡萄牙体育"),
    P("5","Odilon Kossounou","奥迪隆·科索努","Centre-Back","中后卫","Bayer Leverkusen","勒沃库森"),
    P("6","Seko Fofana","塞科·福法纳","Central Midfield","中前卫","Al-Ettifaq","达曼协作"),
    P("7","Franck Kessié","弗兰克·凯西","Central Midfield","中前卫","Al-Ahli","吉达国民"),
    P("8","Ibrahim Sangaré","易卜拉欣·桑加雷","Defensive Midfield","防守中场","Nottingham Forest","诺丁汉森林"),
    P("9","Sébastien Haller","塞巴斯蒂安·阿莱","Centre-Forward","中锋","Borussia Dortmund","多特蒙德"),
    P("10","Simon Adingra","西蒙·阿丁格拉","Winger","边锋","Brighton","布莱顿"),
    P("11","Jonathan Bamba","乔纳森·班巴","Winger","边锋","Celta Vigo","塞尔塔"),
    P("12","Nicolas Pépé","尼古拉·佩佩","Winger","边锋","Villarreal","比利亚雷亚尔"),
    P("13","Jean-Philippe Krasso","让-菲利普·克拉索","Forward","前锋","Saint-Étienne","圣埃蒂安"),
    P("14","Amad Diallo","阿马德·迪亚洛","Winger","边锋","Manchester United","曼联"),
    P("15","Karim Konaté","卡里姆·科纳特","Centre-Forward","中锋","RB Salzburg","萨尔茨堡红牛"),
]}

wiki["Ecuador"] = {"coach":"Sebastián Beccacece","players":[
    P("1","Hernán Galíndez","埃尔南·加林德斯","Goalkeeper","门将","Huracán","飓风"),
    P("12","Moisés Ramírez","莫伊塞斯·拉米雷斯","Goalkeeper","门将","Kifisia","基菲西亚"),
    P("2","Piero Hincapié","皮耶罗·因卡皮耶","Centre-Back","中后卫","Arsenal","阿森纳"),
    P("3","Willian Pacho","威廉·帕乔","Centre-Back","中后卫","Paris SG","巴黎圣日耳曼"),
    P("4","Joel Ordóñez","乔尔·奥多涅斯","Centre-Back","中后卫","Club Brugge","布鲁日"),
    P("5","Pervis Estupiñán","佩维斯·埃斯图皮尼安","Left-Back","左后卫","AC Milan","AC米兰"),
    P("6","Moisés Caicedo","莫伊塞斯·凯塞多","Defensive Midfield","防守中场","Chelsea","切尔西"),
    P("7","Kendry Páez","肯德里·派斯","Attacking Midfield","攻击中场","River Plate","河床"),
    P("8","Alan Franco","阿兰·佛朗哥","Central Midfield","中前卫","Atlético Mineiro","米内罗竞技"),
    P("9","Enner Valencia","恩纳·瓦伦西亚","Centre-Forward","中锋","Pachuca","帕丘卡"),
    P("10","Gonzalo Plata","贡萨洛·普拉塔","Winger","边锋","Flamengo","弗拉门戈"),
    P("11","Kevin Rodríguez","凯文·罗德里格斯","Forward","前锋","Union St-Gilloise","圣吉罗斯联合"),
    P("13","Alan Minda","阿兰·明达","Winger","边锋","Atlético Mineiro","米内罗竞技"),
    P("14","Jeremy Arévalo","杰雷米·阿雷瓦洛","Midfielder","中场","Stuttgart","斯图加特"),
    P("15","Jordy Caicedo","乔迪·凯塞多","Forward","前锋","Huracán","飓风"),
]}

# ===== GROUP F =====
wiki["Netherlands"] = {"coach":"Ronald Koeman","players":[
    P("1","Bart Verbruggen","巴尔特·费布吕亨","Goalkeeper","门将","Brighton","布莱顿"),
    P("13","Robin Roefs","罗宾·鲁夫斯","Goalkeeper","门将","Sunderland","桑德兰"),
    P("23","Mark Flekken","马克·弗莱肯","Goalkeeper","门将","Bayer Leverkusen","勒沃库森"),
    P("4","Virgil van Dijk","维吉尔·范戴克","Centre-Back","中后卫","Liverpool","利物浦"),
    P("5","Nathan Aké","内森·阿克","Left-Back","左后卫","Manchester City","曼城"),
    P("6","Jan Paul van Hecke","扬·保罗·范黑克","Centre-Back","中后卫","Brighton","布莱顿"),
    P("15","Micky van de Ven","米基·范德芬","Centre-Back","中后卫","Tottenham Hotspur","托特纳姆热刺"),
    P("2","Jurriën Timber","朱利安·廷贝尔","Right-Back","右后卫","Arsenal","阿森纳"),
    P("22","Denzel Dumfries","丹泽尔·邓弗里斯","Right-Back","右后卫","Inter Milan","国际米兰"),
    P("12","Mats Wieffer","马茨·维费尔","Defensive Midfield","防守中场","Brighton","布莱顿"),
    P("25","Jorrel Hato","乔雷尔·哈托","Defender","后卫","Chelsea","切尔西"),
    P("21","Frenkie de Jong","弗兰基·德容","Central Midfield","中前卫","Barcelona","巴塞罗那"),
    P("8","Ryan Gravenberch","瑞恩·赫拉芬贝赫","Central Midfield","中前卫","Liverpool","利物浦"),
    P("14","Tijjani Reijnders","泰贾尼·赖因德斯","Central Midfield","中前卫","Manchester City","曼城"),
    P("3","Marten de Roon","马滕·德容恩","Defensive Midfield","防守中场","Atalanta","亚特兰大"),
    P("20","Teun Koopmeiners","特恩·库普梅纳斯","Attacking Midfield","攻击中场","Juventus","尤文图斯"),
    P("16","Guus Til","古斯·蒂尔","Midfielder","中场","PSV Eindhoven","PSV埃因霍温"),
    P("26","Quinten Timber","昆滕·廷贝尔","Midfielder","中场","Marseille","马赛"),
    P("10","Memphis Depay","孟菲斯·德佩","Forward","前锋","Corinthians","科林蒂安"),
    P("11","Cody Gakpo","科迪·加克波","Left Wing","左边锋","Liverpool","利物浦"),
    P("7","Justin Kluivert","贾斯汀·克鲁伊维特","Winger","边锋","Bournemouth","伯恩茅斯"),
    P("9","Wout Weghorst","沃特·韦霍斯特","Centre-Forward","中锋","Ajax","阿贾克斯"),
    P("17","Noa Lang","诺阿·朗","Winger","边锋","Galatasaray","加拉塔萨雷"),
    P("18","Donyell Malen","多尼尔·马伦","Winger","边锋","Roma","罗马"),
    P("19","Brian Brobbey","布莱恩·布罗比","Centre-Forward","中锋","Sunderland","桑德兰"),
    P("24","Crysencio Summerville","克里森西奥·萨默维尔","Winger","边锋","West Ham United","西汉姆联"),
]}

wiki["Japan"] = {"coach":"Hajime Moriyasu","players":[
    P("1","Zion Suzuki","铃木彩艳","Goalkeeper","门将","Parma","帕尔马"),
    P("12","Keisuke Osako","大迫敬介","Goalkeeper","门将","Sanfrecce Hiroshima","广岛三箭"),
    P("23","Tomoki Hayakawa","早川友基","Goalkeeper","门将","Kashima Antlers","鹿岛鹿角"),
    P("2","Yukinari Sugawara","菅原由势","Right-Back","右后卫","Werder Bremen","云达不莱梅"),
    P("3","Shogo Taniguchi","谷口彰悟","Centre-Back","中后卫","Sint-Truiden","圣图尔登"),
    P("4","Ko Itakura","板仓滉","Centre-Back","中后卫","Ajax","阿贾克斯"),
    P("5","Yuto Nagatomo","长友佑都","Left-Back","左后卫","FC Tokyo","FC东京"),
    P("16","Tsuyoshi Watanabe","渡边刚","Centre-Back","中后卫","Feyenoord","费耶诺德"),
    P("20","Ayumu Seko","濑古步梦","Centre-Back","中后卫","Le Havre","勒阿弗尔"),
    P("21","Hiroki Ito","伊藤洋辉","Left-Back","左后卫","Bayern Munich","拜仁慕尼黑"),
    P("22","Takehiro Tomiyasu","富安健洋","Right-Back","右后卫","Ajax","阿贾克斯"),
    P("25","Junnosuke Suzuki","铃木淳之介","Defender","后卫","Copenhagen","哥本哈根"),
    P("6","Wataru Endo","远藤航","Defensive Midfield","防守中场","Liverpool","利物浦"),
    P("7","Ao Tanaka","田中碧","Central Midfield","中前卫","Leeds United","利兹联"),
    P("8","Takefusa Kubo","久保建英","Attacking Midfield","攻击中场","Real Sociedad","皇家社会"),
    P("9","Keisuke Goto","后藤启介","Forward","前锋","Sint-Truiden","圣图尔登"),
    P("10","Ritsu Doan","堂安律","Winger","边锋","Eintracht Frankfurt","法兰克福"),
    P("11","Daizen Maeda","前田大然","Forward","前锋","Celtic","凯尔特人"),
    P("13","Keito Nakamura","中村敬斗","Left Wing","左边锋","Reims","兰斯"),
    P("14","Junya Ito","伊东纯也","Right Winger","右边锋","Genk","亨克"),
    P("15","Daichi Kamada","镰田大地","Attacking Midfield","攻击中场","Crystal Palace","水晶宫"),
    P("17","Yuito Suzuki","铃木唯人","Midfielder","中场","Freiburg","弗赖堡"),
    P("18","Ayase Ueda","上田绮世","Centre-Forward","中锋","Feyenoord","费耶诺德"),
    P("19","Koki Ogawa","小川航基","Centre-Forward","中锋","NEC Nijmegen","奈梅亨"),
    P("24","Kaishu Sano","佐野海舟","Midfielder","中场","Mainz","美因茨"),
    P("26","Kento Shiogai","盐贝健人","Forward","前锋","Wolfsburg","沃尔夫斯堡"),
]}

wiki["Sweden"] = {"coach":"Graham Potter","players":[
    P("1","Viktor Johansson","维克托·约翰松","Goalkeeper","门将","Stoke City","斯托克城"),
    P("12","Kristoffer Nordfeldt","克里斯托弗·诺德费尔特","Goalkeeper","门将","AIK","AIK索尔纳"),
    P("23","Jacob Widell Zetterström","雅各布·泽特斯特伦","Goalkeeper","门将","Derby County","德比郡"),
    P("2","Emil Holm","埃米尔·霍尔姆","Right-Back","右后卫","Juventus","尤文图斯"),
    P("3","Victor Lindelöf","维克托·林德勒夫","Centre-Back","中后卫","Aston Villa","阿斯顿维拉"),
    P("4","Isak Hien","伊萨克·希恩","Centre-Back","中后卫","Atalanta","亚特兰大"),
    P("5","Gabriel Gudmundsson","加布里埃尔·古德蒙德松","Left-Back","左后卫","Leeds United","利兹联"),
    P("14","Carl Starfelt","卡尔·斯塔费尔特","Centre-Back","中后卫","Celta Vigo","塞尔塔"),
    P("16","Daniel Svensson","丹尼尔·斯文松","Left-Back","左后卫","Borussia Dortmund","多特蒙德"),
    P("6","Yasin Ayari","亚辛·阿亚里","Central Midfield","中前卫","Brighton","布莱顿"),
    P("7","Lucas Bergvall","卢卡斯·贝里瓦尔","Central Midfield","中前卫","Tottenham Hotspur","托特纳姆热刺"),
    P("8","Mattias Svanberg","马蒂亚斯·斯万贝里","Central Midfield","中前卫","Wolfsburg","沃尔夫斯堡"),
    P("9","Alexander Isak","亚历山大·伊萨克","Centre-Forward","中锋","Liverpool","利物浦"),
    P("10","Viktor Gyökeres","维克托·哲凯赖什","Centre-Forward","中锋","Arsenal","阿森纳"),
    P("11","Anthony Elanga","安东尼·埃兰加","Winger","边锋","Newcastle United","纽卡斯尔联"),
    P("15","Gustaf Nilsson","古斯塔夫·尼尔松","Forward","前锋","Club Brugge","布鲁日"),
    P("17","Benjamin Nygren","本杰明·尼格伦","Forward","前锋","Celtic","凯尔特人"),
    P("18","Alexander Bernhardsson","亚历山大·伯恩哈德松","Forward","前锋","Holstein Kiel","荷尔斯泰因基尔"),
    P("19","Taha Ali","塔哈·阿里","Winger","边锋","Malmö","马尔默"),
    P("20","Ken Sema","肯·塞马","Midfielder","中场","Pafos","帕福斯"),
    P("21","Jesper Karlström","耶斯珀·卡尔斯特伦","Defensive Midfield","防守中场","Udinese","乌迪内斯"),
]}

wiki["Tunisia"] = {"coach":"Sabri Lamouchi","players":[
    P("1","Sabri Ben Hessen","萨布里·本·赫森","Goalkeeper","门将","Étoile Sahel","沙希尔之星"),
    P("16","Aymen Dahmen","艾门·达门","Goalkeeper","门将","CS Sfaxien","斯法克西恩"),
    P("2","Ali Abdi","阿里·阿卜迪","Left-Back","左后卫","Nice","尼斯"),
    P("3","Montassar Talbi","蒙塔萨尔·塔尔比","Centre-Back","中后卫","Lorient","洛里昂"),
    P("4","Dylan Bronn","迪伦·布龙","Centre-Back","中后卫","Servette Geneva","塞尔维特"),
    P("5","Yan Valery","扬·瓦莱里","Right-Back","右后卫","Young Boys Bern","伯尔尼年轻人"),
    P("6","Ellyes Skhiri","埃利斯·斯希里","Defensive Midfield","防守中场","Eintracht Frankfurt","法兰克福"),
    P("7","Hannibal Mejbri","汉尼拔·梅布里","Central Midfield","中前卫","Burnley","伯恩利"),
    P("8","Anis Ben Slimane","阿尼斯·本·苏莱曼","Central Midfield","中前卫","Norwich City","诺维奇城"),
    P("9","Elias Achouri","埃利亚斯·阿胡里","Winger","边锋","Copenhagen","哥本哈根"),
    P("10","Hazem Mastouri","哈泽姆·马斯图里","Attacking Midfield","攻击中场","Dynamo Makhachkala","马哈奇卡拉迪纳摩"),
    P("11","Sebastian Tounekti","塞巴斯蒂安·图内克蒂","Winger","边锋","Celtic","凯尔特人"),
    P("12","Rani Khedira","拉尼·赫迪拉","Defensive Midfield","防守中场","Union Berlin","柏林联合"),
    P("13","Elias Saad","埃利亚斯·萨阿德","Forward","前锋","Hannover 96","汉诺威96"),
    P("14","Ismaël Gharbi","伊斯梅尔·加尔比","Attacking Midfield","攻击中场","Augsburg","奥格斯堡"),
]}

# ===== GROUP G =====
wiki["Belgium"] = {"coach":"Rudi Garcia","players":[
    P("1","Thibaut Courtois","蒂博·库尔图瓦","Goalkeeper","门将","Real Madrid","皇家马德里"),
    P("12","Senne Lammens","塞内·拉门斯","Goalkeeper","门将","Club Brugge","布鲁日"),
    P("13","Mike Penders","迈克·彭德斯","Goalkeeper","门将","Chelsea","切尔西"),
    P("2","Timothy Castagne","蒂莫西·卡斯塔涅","Right-Back","右后卫","Fulham","富勒姆"),
    P("3","Zeno Debast","泽诺·德巴斯特","Centre-Back","中后卫","Sporting CP","葡萄牙体育"),
    P("4","Wout Faes","沃特·法斯","Centre-Back","中后卫","Leicester City","莱斯特城"),
    P("5","Maxim De Cuyper","马克西姆·德克伊珀","Left-Back","左后卫","Brighton","布莱顿"),
    P("15","Koni De Winter","科尼·德温特","Centre-Back","中后卫","AC Milan","AC米兰"),
    P("16","Thomas Meunier","托马斯·默尼耶","Right-Back","右后卫","Lille","里尔"),
    P("6","Kevin De Bruyne","凯文·德布劳内","Attacking Midfield","攻击中场","Manchester City","曼城"),
    P("7","Amadou Onana","阿马杜·奥纳纳","Defensive Midfield","防守中场","Aston Villa","阿斯顿维拉"),
    P("8","Youri Tielemans","尤里·蒂勒曼斯","Central Midfield","中前卫","Aston Villa","阿斯顿维拉"),
    P("14","Nicolas Raskin","尼古拉·拉斯金","Midfielder","中场","Rangers","流浪者"),
    P("17","Hans Vanaken","汉斯·瓦纳肯","Attacking Midfield","攻击中场","Club Brugge","布鲁日"),
    P("18","Axel Witsel","阿克塞尔·维特塞尔","Defensive Midfield","防守中场","Atlético Madrid","马德里竞技"),
    P("9","Romelu Lukaku","罗梅卢·卢卡库","Centre-Forward","中锋","Napoli","那不勒斯"),
    P("10","Charles De Ketelaere","夏尔·德凯特拉雷","Attacking Midfield","攻击中场","Atalanta","亚特兰大"),
    P("11","Jérémy Doku","热雷米·多库","Winger","边锋","Manchester City","曼城"),
    P("19","Leandro Trossard","莱安德罗·特罗萨德","Winger","边锋","Arsenal","阿森纳"),
    P("20","Dodi Lukebakio","多迪·卢克巴基奥","Winger","边锋","Benfica","本菲卡"),
    P("21","Diego Moreira","迭戈·莫雷拉","Winger","边锋","Strasbourg","斯特拉斯堡"),
    P("22","Alexis Saelemaekers","亚历克西斯·萨勒马克尔斯","Winger","边锋","AC Milan","AC米兰"),
    P("23","Matias Fernandez-Pardo","马蒂亚斯·费尔南德斯-帕尔多","Forward","前锋","Lille","里尔"),
]}

wiki["Egypt"] = {"coach":"Hossam Hassan","players":[
    P("1","Mohamed El Shenawy","穆罕默德·谢纳维","Goalkeeper","门将","Al Ahly","开罗国民"),
    P("16","Mostafa Shobeir","穆斯塔法·舒贝尔","Goalkeeper","门将","Al Ahly","开罗国民"),
    P("23","El Mahdy Soliman","马赫迪·苏莱曼","Goalkeeper","门将","Zamalek","扎马雷克"),
    P("2","Mohamed Hany","穆罕默德·哈尼","Right-Back","右后卫","Al Ahly","开罗国民"),
    P("3","Mohamed Abdelmonem","穆罕默德·阿卜杜勒莫内姆","Centre-Back","中后卫","Nice","尼斯"),
    P("4","Ramy Rabia","拉米·拉比亚","Centre-Back","中后卫","Al Ain","艾因"),
    P("5","Ahmed Fatouh","艾哈迈德·法图赫","Left-Back","左后卫","Zamalek","扎马雷克"),
    P("6","Yasser Ibrahim","亚西尔·易卜拉欣","Centre-Back","中后卫","Al Ahly","开罗国民"),
    P("7","Hamdy Fathy","哈姆迪·法特希","Defensive Midfield","防守中场","Al Wakrah","沃克拉"),
    P("8","Emam Ashour","伊马姆·阿舒尔","Central Midfield","中前卫","Al Ahly","开罗国民"),
    P("9","Ahmed Zizo","艾哈迈德·齐佐","Winger","边锋","Zamalek","扎马雷克"),
    P("10","Mahmoud Trezeguet","马哈茂德·特雷泽盖","Winger","边锋","Trabzonspor","特拉布宗体育"),
    P("11","Omar Marmoush","奥马尔·马尔穆什","Forward","前锋","Manchester City","曼城"),
    P("12","Mohamed Salah","穆罕默德·萨拉赫","Right Winger","右边锋","Liverpool","利物浦"),
    P("13","Ibrahim Adel","易卜拉欣·阿德尔","Winger","边锋","Pyramids","金字塔"),
    P("14","Marwan Ateya","马尔万·阿提亚","Midfielder","中场","Al Ahly","开罗国民"),
    P("15","Nabil Emad","纳比勒·伊马德","Defensive Midfield","防守中场","Zamalek","扎马雷克"),
    P("17","Mahmoud Saber","马哈茂德·萨贝尔","Midfielder","中场","Pyramids","金字塔"),
    P("18","Mostafa Ziko","穆斯塔法·齐科","Winger","边锋","Zamalek","扎马雷克"),
    P("19","Haissem Hassan","海塞姆·哈桑","Forward","前锋","Al Ahly","开罗国民"),
]}

wiki["Iran"] = {"coach":"Amir Ghalenoei","players":[
    P("1","Alireza Beiranvand","阿里雷扎·贝兰万德","Goalkeeper","门将","Persepolis","波斯波利斯"),
    P("12","Payam Niazmand","佩亚姆·尼亚兹曼德","Goalkeeper","门将","Sepahan","塞帕罕"),
    P("22","Hossein Hosseini","侯赛因·侯赛尼","Goalkeeper","门将","Esteghlal","德黑兰独立"),
    P("2","Shoja Khalilzadeh","肖贾·哈利勒扎德","Centre-Back","中后卫","Tractor","拖拉机"),
    P("3","Hossein Kanaani","侯赛因·卡纳尼","Centre-Back","中后卫","Persepolis","波斯波利斯"),
    P("4","Morteza Pouraliganji","莫尔塔扎·普拉利甘吉","Centre-Back","中后卫","Persepolis","波斯波利斯"),
    P("5","Milad Mohammadi","米拉德·穆罕默迪","Left-Back","左后卫","AEK Athens","雅典AEK"),
    P("6","Saeid Ezatolahi","赛义德·埃扎托拉希","Defensive Midfield","防守中场","Shabab Al-Ahli","迪拜青年国民"),
    P("7","Alireza Jahanbakhsh","阿里雷扎·贾汉巴赫什","Winger","边锋","Feyenoord","费耶诺德"),
    P("8","Saman Ghoddos","萨曼·戈多斯","Attacking Midfield","攻击中场","Brentford","布伦特福德"),
    P("9","Mehdi Taremi","迈赫迪·塔雷米","Centre-Forward","中锋","Inter Milan","国际米兰"),
    P("10","Sardar Azmoun","萨达尔·阿兹蒙","Centre-Forward","中锋","Roma","罗马"),
    P("11","Mehdi Ghayedi","迈赫迪·加耶迪","Winger","边锋","Al-Ittihad Kalba","卡尔巴联合"),
    P("13","Ali Gholizadeh","阿里·戈利扎德","Winger","边锋","Lech Poznań","波兹南莱赫"),
    P("14","Mohammad Mohebi","穆罕默德·莫赫比","Winger","边锋","Rostov","罗斯托夫"),
]}

wiki["New Zealand"] = {"coach":"Darren Bazeley","players":[
    P("1","Max Crocombe","马克斯·克罗科姆","Goalkeeper","门将","Burton Albion","伯顿"),
    P("12","Alex Paulsen","亚历克斯·保尔森","Goalkeeper","门将","AFC Bournemouth","伯恩茅斯"),
    P("2","Bill Tuiloma","比尔·图伊洛马","Centre-Back","中后卫","Charlotte FC","夏洛特FC"),
    P("3","Nando Pijnaker","南多·派纳克","Centre-Back","中后卫","Sligo Rovers","斯莱戈流浪者"),
    P("4","Michael Boxall","迈克尔·博克索尔","Centre-Back","中后卫","Minnesota United","明尼苏达联"),
    P("5","Tommy Smith","汤米·史密斯","Centre-Back","中后卫","Auckland FC","奥克兰FC"),
    P("6","Joe Bell","乔·贝尔","Defensive Midfield","防守中场","Viking FK","维京"),
    P("7","Sarpreet Singh","萨普里特·辛格","Attacking Midfield","攻击中场","Hansa Rostock","罗斯托克"),
    P("8","Marko Stamenic","马尔科·斯塔梅尼奇","Central Midfield","中前卫","Olympiacos","奥林匹亚科斯"),
    P("9","Chris Wood","克里斯·伍德","Centre-Forward","中锋","Nottingham Forest","诺丁汉森林"),
    P("10","Ben Waine","本·韦恩","Forward","前锋","Plymouth Argyle","普利茅斯"),
    P("11","Elijah Just","以利亚·贾斯特","Winger","边锋","St. Pölten","圣珀尔滕"),
    P("13","Matthew Garbett","马修·加贝特","Midfielder","中场","NAC Breda","布雷达"),
    P("14","Callum McCowatt","卡勒姆·麦考瓦特","Winger","边锋","Silkeborg","锡尔克堡"),
    P("15","Kosta Barbarouses","科斯塔·巴巴鲁塞斯","Forward","前锋","Wellington Phoenix","惠灵顿凤凰"),
]}

# Save
json.dump(wiki, open('wiki_squads.json','w',encoding='utf-8'), ensure_ascii=False, indent=2)
total = sum(len(t['players']) for t in wiki.values())
print(f'Part 2 done: {len(wiki)} teams, {total} players')
