#!/usr/bin/env python3
"""Build complete wiki_squads.json with all collected squad data."""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def p(num, name, cn, pos, poscn, club, clubcn):
    """Shorthand to create player dict"""
    return {"number":num,"name":name,"name_cn":cn,"position":pos,"position_cn":poscn,"club":club,"club_cn":clubcn}

# Load existing 5 teams
wiki = json.load(open('wiki_squads.json', encoding='utf-8'))

# ===== GROUP A =====
wiki["South Korea"] = {"coach":"洪明甫","players":[
    p("1","Kim Seung-gyu","金承奎","Goalkeeper","门将","FC Tokyo","FC东京"),
    p("12","Song Bum-keun","宋范根","Goalkeeper","门将","Jeonbuk Hyundai","全北现代"),
    p("21","Jo Hyeon-woo","赵贤祐","Goalkeeper","门将","Ulsan HD","蔚山HD"),
    p("4","Kim Min-jae","金玟哉","Centre-Back","中后卫","Bayern Munich","拜仁慕尼黑"),
    p("2","Lee Han-beom","李韩汎","Centre-Back","中后卫","FC Midtjylland","中日德兰"),
    p("3","Lee Ki-hyuk","李期奕","Defender","后卫","Gangwon FC","江原FC"),
    p("14","Cho Wi-je","赵伟济","Defender","后卫","Jeonbuk Hyundai","全北现代"),
    p("15","Kim Moon-hwan","金纹焕","Right-Back","右后卫","Daejeon Hana","大田韩亚"),
    p("22","Seol Young-woo","薛英佑","Left-Back","左后卫","Red Star Belgrade","贝尔格莱德红星"),
    p("23","Jens Castrop","延斯·卡斯特罗普","Defender","后卫","Borussia Mönchengladbach","门兴"),
    p("6","Hwang In-beom","黄仁范","Central Midfield","中前卫","Feyenoord","费耶诺德"),
    p("8","Paik Seung-ho","白昇浩","Midfielder","中场","Birmingham City","伯明翰城"),
    p("10","Lee Jae-sung","李在城","Midfielder","中场","Mainz","美因茨"),
    p("11","Hwang Hee-chan","黄喜灿","Left Wing","左边锋","Wolves","狼队"),
    p("16","Park Jin-seop","朴镇燮","Midfielder","中场","Zhejiang FC","浙江FC"),
    p("19","Lee Kang-in","李刚仁","Attacking Midfield","攻击中场","Paris SG","巴黎圣日耳曼"),
    p("20","Yang Hyun-jun","杨贤俊","Winger","边锋","Celtic","凯尔特人"),
    p("25","Eom Ji-sung","严智星","Winger","边锋","Swansea City","斯旺西城"),
    p("7","Son Heung-min","孙兴慜","Left Wing","左边锋","Los Angeles FC","洛杉矶FC"),
    p("9","Cho Gue-sung","曹圭成","Centre-Forward","中锋","FC Midtjylland","中日德兰"),
    p("18","Oh Hyeon-gyu","吴贤揆","Centre-Forward","中锋","Beşiktaş","贝西克塔什"),
    p("17","Bae Jun-ho","裴俊浩","Midfielder","中场","Stoke City","斯托克城"),
    p("24","Kim Jin-gyu","金镇圭","Midfielder","中场","Jeonbuk Hyundai","全北现代"),
    p("26","Lee Dong-gyeong","李东炅","Midfielder","中场","Ulsan HD","蔚山HD"),
    p("5","Kim Tae-hyeon","金太铉","Defender","后卫","Kashima Antlers","鹿岛鹿角"),
    p("13","Lee Tae-seok","李太锡","Defender","后卫","Austria Wien","奥地利维也纳"),
]}

wiki["Mexico"] = {"coach":"Javier Aguirre","players":[
    p("1","Guillermo Ochoa","吉列尔莫·奥乔亚","Goalkeeper","门将","AEL Limassol","AEL利马索尔"),
    p("12","José Rangel","何塞·兰格尔","Goalkeeper","门将","CD Guadalajara","瓜达拉哈拉"),
    p("23","Carlos Acevedo","卡洛斯·阿切维多","Goalkeeper","门将","Santos Laguna","桑托斯拉古纳"),
    p("2","Jorge Sánchez","豪尔赫·桑切斯","Right-Back","右后卫","PAOK","塞萨洛尼基"),
    p("3","César Montes","塞萨尔·蒙特斯","Centre-Back","中后卫","Lokomotiv Moscow","莫斯科火车头"),
    p("4","Johan Vásquez","约翰·巴斯克斯","Centre-Back","中后卫","Genoa","热那亚"),
    p("5","Jesús Gallardo","赫苏斯·加利亚多","Left-Back","左后卫","Toluca","托卢卡"),
    p("13","Israel Reyes","伊塞尔·雷耶斯","Defender","后卫","Club América","美洲队"),
    p("6","Edson Álvarez","埃德森·阿尔瓦雷斯","Defensive Midfield","防守中场","Fenerbahçe","费内巴切"),
    p("7","Luis Romo","路易斯·罗莫","Central Midfield","中前卫","CD Guadalajara","瓜达拉哈拉"),
    p("8","Álvaro Fidalgo","阿尔瓦罗·菲达尔戈","Central Midfield","中前卫","Real Betis","皇家贝蒂斯"),
    p("14","Brian Gutiérrez","布莱恩·古铁雷斯","Midfielder","中场","CD Guadalajara","瓜达拉哈拉"),
    p("15","Obed Vargas","奥贝德·巴尔加斯","Midfielder","中场","Atlético Madrid","马德里竞技"),
    p("18","Luis Chávez","路易斯·查韦斯","Central Midfield","中前卫","Dynamo Moscow","莫斯科迪纳摩"),
    p("9","Santiago Giménez","圣地亚哥·希门尼斯","Centre-Forward","中锋","AC Milan","AC米兰"),
    p("10","Raúl Jiménez","劳尔·希门尼斯","Centre-Forward","中锋","Fulham","富勒姆"),
    p("11","Alexis Vega","阿莱克斯·维加","Left Wing","左边锋","Toluca","托卢卡"),
    p("17","Roberto Alvarado","罗伯托·阿尔瓦拉多","Winger","边锋","CD Guadalajara","瓜达拉哈拉"),
    p("19","César Huerta","塞萨尔·韦尔塔","Winger","边锋","Anderlecht","安德莱赫特"),
    p("22","Armando González","阿曼多·冈萨雷斯","Forward","前锋","CD Guadalajara","瓜达拉哈拉"),
    p("25","Guillermo Martínez","吉列尔莫·马丁内斯","Forward","前锋","Pumas","美洲狮"),
    p("26","Julián Quiñones","奎尼奥内斯","Forward","前锋","Al-Qadsiah","胡拜尔库迪西亚"),
    p("20","Erik Lira","埃里克·里拉","Defensive Midfield","防守中场","Cruz Azul","蓝十字"),
    p("21","Gilberto Mora","希尔韦托·莫拉","Midfielder","中场","Tijuana","蒂华纳"),
    p("24","Orbelín Pineda","皮内达","Midfielder","中场","AEK Athens","雅典AEK"),
    p("16","Mateo Chávez","马特奥·查韦斯","Left-Back","左后卫","AZ Alkmaar","阿尔克马尔"),
]}

wiki["Czech Republic"] = {"coach":"Ivan Hašek","players":[
    p("1","Matěj Kovář","马泰·科瓦日","Goalkeeper","门将","PSV Eindhoven","PSV埃因霍温"),
    p("16","Jindřich Staněk","因德里奇·斯塔涅克","Goalkeeper","门将","Slavia Prague","布拉格斯拉维亚"),
    p("23","Lukáš Horníček","卢卡斯·霍尔尼切克","Goalkeeper","门将","Braga","布拉加"),
    p("2","David Zima","大卫·齐马","Centre-Back","中后卫","Slavia Prague","布拉格斯拉维亚"),
    p("3","Tomáš Holeš","托马斯·霍莱什","Centre-Back","中后卫","Slavia Prague","布拉格斯拉维亚"),
    p("4","Robin Hranáč","罗宾·赫拉纳奇","Centre-Back","中后卫","Hoffenheim","霍芬海姆"),
    p("5","Vladimír Coufal","弗拉基米尔·曹法尔","Right-Back","右后卫","Hoffenheim","霍芬海姆"),
    p("7","Ladislav Krejčí","拉迪斯拉夫·克雷伊奇","Centre-Back","中后卫","Wolves","狼队"),
    p("14","David Jurásek","大卫·尤拉塞克","Left-Back","左后卫","Slavia Prague","布拉格斯拉维亚"),
    p("20","Jaroslav Zelený","雅罗斯拉夫·泽勒尼","Left-Back","左后卫","Sparta Prague","布拉格斯巴达"),
    p("8","Vladimír Darida","弗拉基米尔·达里达","Central Midfield","中前卫","Hradec Králové","赫拉德茨克拉洛韦"),
    p("15","Pavel Šulc","帕维尔·舒尔茨","Attacking Midfield","攻击中场","Lyon","里昂"),
    p("17","Lukáš Provod","卢卡斯·普罗沃德","Midfielder","中场","Slavia Prague","布拉格斯拉维亚"),
    p("18","Michal Sadílek","米哈尔·萨迪莱克","Midfielder","中场","Slavia Prague","布拉格斯拉维亚"),
    p("22","Tomáš Souček","托马斯·绍切克","Central Midfield","中前卫","West Ham United","西汉姆联"),
    p("6","Štěpán Chaloupek","什捷潘·哈劳佩克","Defender","后卫","Slavia Prague","布拉格斯拉维亚"),
    p("9","Adam Hložek","亚当·赫洛热克","Forward","前锋","Hoffenheim","霍芬海姆"),
    p("10","Patrik Schick","帕特里克·希克","Centre-Forward","中锋","Bayer Leverkusen","勒沃库森"),
    p("11","Jan Kuchta","扬·库赫塔","Centre-Forward","中锋","Sparta Prague","布拉格斯巴达"),
    p("13","Mojmír Chytil","莫伊米尔·希季尔","Forward","前锋","Slavia Prague","布拉格斯拉维亚"),
    p("19","Tomáš Chorý","托马什·绍里","Centre-Forward","中锋","Slavia Prague","布拉格斯拉维亚"),
    p("12","Lukáš Červ","卢卡斯·切尔夫","Midfielder","中场","Viktoria Plzeň","比尔森胜利"),
    p("21","David Douděra","大卫·道杰拉","Defender","后卫","Slavia Prague","布拉格斯拉维亚"),
    p("24","Alexandr Sojka","亚历山大·索伊卡","Midfielder","中场","Viktoria Plzeň","比尔森胜利"),
    p("25","Hugo Schuhurek","乌戈·索胡雷克","Midfielder","中场","Sparta Prague","布拉格斯巴达"),
    p("26","Denis Višinský","丹尼斯·维辛斯基","Midfielder","中场","Viktoria Plzeň","比尔森胜利"),
]}

wiki["South Africa"] = {"coach":"Hugo Broos","players":[
    p("1","Ronwen Williams","罗恩文·威廉姆斯","Goalkeeper","门将","Mamelodi Sundowns","马梅洛迪日落"),
    p("16","Ricardo Goss","里卡多·戈斯","Goalkeeper","门将","SuperSport United","超级体育联"),
    p("23","Sipho Chaine","西波·钱恩","Goalkeeper","门将","Orlando Pirates","奥兰多海盗"),
    p("2","Kuliso Mudau","库利索·穆达乌","Right-Back","右后卫","Mamelodi Sundowns","马梅洛迪日落"),
    p("3","Nkosinathi Sibisi","恩科西纳蒂·西比西","Centre-Back","中后卫","Orlando Pirates","奥兰多海盗"),
    p("4","Ime Okon","伊梅·奥孔","Centre-Back","中后卫","Hannover 96","汉诺威96"),
    p("5","Kulumani Ndamane","库卢马尼·恩达马内","Centre-Back","中后卫","Mamelodi Sundowns","马梅洛迪日落"),
    p("6","Aubrey Modiba","奥布雷·莫迪巴","Left-Back","左后卫","Mamelodi Sundowns","马梅洛迪日落"),
    p("14","Samukelo Kabini","萨穆凯洛·卡比尼","Defender","后卫","Molde FK","莫尔德"),
    p("15","Olwethu Makhanya","奥尔韦图·马卡尼亚","Defender","后卫","Philadelphia Union","费城联合"),
    p("19","Bradley Cross","布拉德利·克罗斯","Centre-Back","中后卫","Kaizer Chiefs","凯撒酋长"),
    p("7","Teboho Mokoena","泰博霍·莫科纳","Central Midfield","中前卫","Mamelodi Sundowns","马梅洛迪日落"),
    p("8","Talent Mbatha","塔伦特·姆巴塔","Midfielder","中场","Orlando Pirates","奥兰多海盗"),
    p("12","Sphephelo Sithole","斯皮菲洛·西索莱","Midfielder","中场","CD Tondela","CD通德拉"),
    p("20","Jayden Adams","杰登·亚当斯","Midfielder","中场","Mamelodi Sundowns","马梅洛迪日落"),
    p("9","Lyle Foster","莱尔·福斯特","Centre-Forward","中锋","Burnley","伯恩利"),
    p("10","Oswin Appollis","奥斯温·阿波利斯","Winger","边锋","Orlando Pirates","奥兰多海盗"),
    p("11","Iqraam Rayners","伊克拉姆·雷纳斯","Forward","前锋","Mamelodi Sundowns","马梅洛迪日落"),
    p("17","Evidence Makgopa","埃维登斯·马科戈帕","Centre-Forward","中锋","Orlando Pirates","奥兰多海盗"),
    p("18","Relebohile Mofokeng","雷莱博希莱·莫福肯","Winger","边锋","Orlando Pirates","奥兰多海盗"),
    p("21","Themba Zwane","滕巴·兹瓦内","Attacking Midfield","攻击中场","Mamelodi Sundowns","马梅洛迪日落"),
    p("24","Thapelo Maseko","塔佩洛·马塞科","Winger","边锋","AEL Limassol","AEL利马索尔"),
]}

# ===== GROUP B =====
wiki["Canada"] = {"coach":"Jesse Marsch","players":[
    p("1","Dayne St. Clair","戴恩·圣克莱尔","Goalkeeper","门将","Minnesota United","明尼苏达联"),
    p("16","Maxime Crépeau","马克西姆·克雷波","Goalkeeper","门将","Portland Timbers","波特兰伐木者"),
    p("18","Jonathan Sirois","乔纳森·西罗伊斯","Goalkeeper","门将","CF Montréal","蒙特利尔CF"),
    p("2","Alistair Johnston","阿利斯泰尔·约翰斯顿","Right-Back","右后卫","Celtic","凯尔特人"),
    p("3","Alphonso Davies","阿方索·戴维斯","Left-Back","左后卫","Bayern Munich","拜仁慕尼黑"),
    p("4","Derek Cornelius","德里克·科尼利厄斯","Centre-Back","中后卫","Marseille","马赛"),
    p("5","Moïse Bombito","莫伊兹·邦比托","Centre-Back","中后卫","Nice","尼斯"),
    p("15","Kamal Miller","卡马尔·米勒","Centre-Back","中后卫","Portland Timbers","波特兰伐木者"),
    p("6","Stephen Eustáquio","斯蒂芬·欧斯塔基奥","Central Midfield","中前卫","FC Porto","波尔图"),
    p("7","Tajon Buchanan","塔琼·布坎南","Winger","边锋","Inter Milan","国际米兰"),
    p("8","Ismaël Koné","伊斯梅尔·科内","Central Midfield","中前卫","Marseille","马赛"),
    p("14","Mathieu Choinière","马修·舒瓦尼埃","Midfielder","中场","CF Montréal","蒙特利尔CF"),
    p("21","Jonathan Osorio","乔纳森·奥索里奥","Central Midfield","中前卫","Toronto FC","多伦多FC"),
    p("9","Cyle Larin","赛尔·拉林","Centre-Forward","中锋","Mallorca","马略卡"),
    p("10","Jonathan David","乔纳森·戴维","Centre-Forward","中锋","Lille","里尔"),
    p("11","Liam Millar","利亚姆·米勒","Winger","边锋","FC Basel","巴塞尔"),
    p("17","Jacen Russell-Rowe","杰森·拉塞尔-罗","Forward","前锋","Columbus Crew","哥伦布机员"),
    p("19","Iké Ugbo","伊克·乌格博","Centre-Forward","中锋","Sheffield Wednesday","谢周三"),
    p("23","Luca Koleosho","卢卡·科莱奥肖","Forward","前锋","Burnley","伯恩利"),
    p("13","Richie Laryea","里奇·拉里亚","Defender","后卫","Toronto FC","多伦多FC"),
    p("12","Steven Vitória","史蒂文·维多利亚","Centre-Back","中后卫","Chaves","查韦斯"),
    p("20","Theo Corbeanu","特奥·科尔贝亚努","Winger","边锋","Granada","格拉纳达"),
    p("22","Joel Waterman","乔尔·沃特曼","Defender","后卫","CF Montréal","蒙特利尔CF"),
    p("24","Ali Ahmed","阿里·艾哈迈德","Midfielder","中场","Vancouver Whitecaps","温哥华白帽"),
    p("25","Kyle Hiebert","凯尔·希伯特","Defender","后卫","St. Louis City","圣路易斯城"),
    p("26","Ayo Akinola","阿约·阿基诺拉","Forward","前锋","San Jose Earthquakes","圣何塞地震"),
]}

wiki["Bosnia & Herzegovina"] = {"coach":"Faruk Hadžibegić","players":[
    p("1","Ibrahim Šehić","易卜拉欣·谢希奇","Goalkeeper","门将","Al-Khaleej","海湾"),
    p("12","Nikola Vasilj","尼古拉·瓦西里","Goalkeeper","门将","St. Pauli","圣保利"),
    p("3","Sead Kolašinac","塞亚德·科拉希纳茨","Left-Back","左后卫","Atalanta","亚特兰大"),
    p("4","Anel Ahmedhodžić","阿内尔·艾哈迈德霍季奇","Centre-Back","中后卫","Sheffield United","谢菲联"),
    p("5","Dennis Hadžikadunić","丹尼斯·哈季卡杜尼奇","Centre-Back","中后卫","Hamburger SV","汉堡"),
    p("6","Adrian Leon Barišić","阿德里安·巴里希奇","Centre-Back","中后卫","FC Basel","巴塞尔"),
    p("2","Jusuf Gazibegović","优素福·加齐贝戈维奇","Right-Back","右后卫","Sturm Graz","格拉茨风暴"),
    p("13","Amar Dedić","阿马尔·德迪奇","Right-Back","右后卫","RB Salzburg","萨尔茨堡红牛"),
    p("7","Rade Krunić","拉德·克鲁尼奇","Central Midfield","中前卫","Fenerbahçe","费内巴切"),
    p("8","Miralem Pjanić","米拉莱姆·皮亚尼奇","Central Midfield","中前卫","Sharjah FC","沙迦"),
    p("10","Amir Hadžiahmetović","阿米尔·哈季亚赫梅托维奇","Defensive Midfield","防守中场","Beşiktaş","贝西克塔什"),
    p("15","Benjamin Tahirović","本杰明·塔希罗维奇","Midfielder","中场","Ajax","阿贾克斯"),
    p("17","Amar Rahmanović","阿马尔·拉赫马诺维奇","Midfielder","中场","Krylya Sovetov","苏维埃之翼"),
    p("9","Edin Džeko","埃丁·哲科","Centre-Forward","中锋","Fenerbahçe","费内巴切"),
    p("11","Ermedin Demirović","埃尔梅丁·德米罗维奇","Centre-Forward","中锋","VfB Stuttgart","斯图加特"),
    p("20","Smail Prevljak","斯马伊尔·普雷维亚克","Forward","前锋","Hertha Berlin","柏林赫塔"),
    p("21","Luka Jović","卢卡·约维奇","Centre-Forward","中锋","AC Milan","AC米兰"),
    p("22","Kenan Kodro","凯南·科德罗","Forward","前锋","Ferencváros","费伦茨瓦罗斯"),
]}

wiki["Qatar"] = {"coach":"Félix Sánchez","players":[
    p("1","Meshaal Barsham","梅沙尔·巴沙姆","Goalkeeper","门将","Al-Sadd","萨德"),
    p("21","Salah Zakaria","萨拉赫·扎卡里亚","Goalkeeper","门将","Al-Duhail","杜海勒"),
    p("2","Boualem Khoukhi","布阿莱姆·胡赫","Centre-Back","中后卫","Al-Sadd","萨德"),
    p("3","Abdelkarim Hassan","阿卜杜勒卡里姆·哈桑","Left-Back","左后卫","Al-Sadd","萨德"),
    p("5","Tarek Salman","塔里克·萨勒曼","Centre-Back","中后卫","Al-Sadd","萨德"),
    p("14","Homam Ahmed","霍马姆·艾哈迈德","Left-Back","左后卫","Al-Gharafa","加拉法"),
    p("15","Bassam Al-Rawi","巴萨姆·拉维","Centre-Back","中后卫","Al-Duhail","杜海勒"),
    p("6","Abdulaziz Hatem","阿卜杜勒阿齐兹·哈特姆","Central Midfield","中前卫","Al-Rayyan","赖扬"),
    p("10","Akram Afif","阿克拉姆·阿菲夫","Attacking Midfield","攻击中场","Al-Sadd","萨德"),
    p("12","Karim Boudiaf","卡里姆·布迪亚夫","Defensive Midfield","防守中场","Al-Duhail","杜海勒"),
    p("20","Mostafa Meshaal","穆斯塔法·梅沙尔","Midfielder","中场","Al-Sadd","萨德"),
    p("7","Almoez Ali","阿尔莫埃斯·阿里","Centre-Forward","中锋","Al-Duhail","杜海勒"),
    p("9","Ahmed Alaaeldin","艾哈迈德·阿拉丁","Forward","前锋","Al-Gharafa","加拉法"),
    p("11","Yusuf Abdurisag","优素福·阿卜杜里萨格","Winger","边锋","Al-Sadd","萨德"),
    p("18","Mohammed Muntari","穆罕默德·蒙塔里","Centre-Forward","中锋","Al-Duhail","杜海勒"),
    p("19","Ismaeel Mohammad","伊斯梅尔·穆罕默德","Winger","边锋","Al-Duhail","杜海勒"),
]}

# ===== GROUP C (Morocco, Scotland, Haiti) =====
wiki["Morocco"] = {"coach":"Mohamed Ouahbi","players":[
    p("1","Yassine Bounou","亚辛·布努","Goalkeeper","门将","Al-Hilal","利雅得新月"),
    p("12","Munir El Kajoui","穆尼尔·卡维","Goalkeeper","门将","RS Berkane","RS贝尔卡内"),
    p("22","Ahmed Reda Tagnaouti","艾哈迈德·塔格纳乌蒂","Goalkeeper","门将","AS FAR","皇家武装部队"),
    p("2","Achraf Hakimi","阿什拉夫·哈基米","Right-Back","右后卫","Paris SG","巴黎圣日耳曼"),
    p("3","Noussair Mazraoui","努赛尔·马兹拉维","Left-Back","左后卫","Manchester United","曼联"),
    p("5","Nayef Aguerd","纳耶夫·阿格尔德","Centre-Back","中后卫","Marseille","马赛"),
    p("6","Chadi Riad","沙迪·里亚德","Centre-Back","中后卫","Crystal Palace","水晶宫"),
    p("4","Issa Diop","伊萨·迪奥普","Centre-Back","中后卫","Fulham","富勒姆"),
    p("8","Sofyan Amrabat","索菲扬·阿姆拉巴特","Defensive Midfield","防守中场","Real Betis","皇家贝蒂斯"),
    p("10","Azzedine Ounahi","阿泽丁·乌纳希","Central Midfield","中前卫","Girona","赫罗纳"),
    p("15","Bilal El Khannouss","比拉尔·汉努斯","Attacking Midfield","攻击中场","Stuttgart","斯图加特"),
    p("14","Ismael Saibari","伊斯梅尔·赛巴里","Central Midfield","中前卫","PSV Eindhoven","PSV埃因霍温"),
    p("18","Ayyoub Bouaddi","阿尤布·布阿迪","Midfielder","中场","Lille","里尔"),
    p("7","Brahim Díaz","卜拉欣·迪亚斯","Attacking Midfield","攻击中场","Real Madrid","皇家马德里"),
    p("17","Abde Ezzalzouli","阿卜德·埃扎尔祖利","Left Wing","左边锋","Real Betis","皇家贝蒂斯"),
    p("9","Ayoub El Kaabi","阿尤布·卡比","Centre-Forward","中锋","Olympiacos","奥林匹亚科斯"),
    p("11","Soufiane Rahimi","苏菲安·拉希米","Forward","前锋","Al Ain","艾因"),
    p("19","Chemsdine Talbi","切姆西丁·塔尔比","Forward","前锋","Sunderland","桑德兰"),
    p("20","Yassine Gessime","亚辛·格西姆","Forward","前锋","Strasbourg","斯特拉斯堡"),
    p("13","Zakaria El Ouahdi","扎卡里亚·瓦赫迪","Defender","后卫","Genk","亨克"),
    p("16","Neil El Aynaoui","尼尔·艾纳维","Midfielder","中场","Roma","罗马"),
    p("21","Ayoube Amaimouni","阿尤布·阿迈穆尼","Forward","前锋","Eintracht Frankfurt","法兰克福"),
    p("23","Redouane Halhal","雷杜万·哈尔哈尔","Defender","后卫","KV Mechelen","梅赫伦"),
    p("24","Youssef Belammari","优素福·贝拉马里","Defender","后卫","Al Ahly","开罗国民"),
    p("25","Anass Salah-Eddine","阿纳斯·萨拉赫丁","Defender","后卫","PSV Eindhoven","PSV埃因霍温"),
    p("26","Samir El Mourabet","萨米尔·穆拉贝","Midfielder","中场","Strasbourg","斯特拉斯堡"),
]}

wiki["Scotland"] = {"coach":"Steve Clarke","players":[
    p("1","Craig Gordon","克雷格·戈登","Goalkeeper","门将","Hearts","哈茨"),
    p("12","Angus Gunn","安格斯·冈恩","Goalkeeper","门将","Nottingham Forest","诺丁汉森林"),
    p("21","Liam Kelly","利亚姆·凯利","Goalkeeper","门将","Rangers","流浪者"),
    p("2","Andy Robertson","安迪·罗伯逊","Left-Back","左后卫","Liverpool","利物浦"),
    p("3","Kieran Tierney","基兰·蒂尔尼","Centre-Back","中后卫","Celtic","凯尔特人"),
    p("5","Grant Hanley","格兰特·汉利","Centre-Back","中后卫","Hibernian","希伯尼安"),
    p("6","John Souttar","约翰·苏塔尔","Centre-Back","中后卫","Rangers","流浪者"),
    p("13","Scott McKenna","斯科特·麦肯纳","Centre-Back","中后卫","Dinamo Zagreb","萨格勒布迪纳摩"),
    p("15","Aaron Hickey","阿龙·希基","Right-Back","右后卫","Brentford","布伦特福德"),
    p("16","Nathan Patterson","内森·帕特森","Right-Back","右后卫","Everton","埃弗顿"),
    p("4","Scott McTominay","斯科特·麦克托米奈","Central Midfield","中前卫","Napoli","那不勒斯"),
    p("7","John McGinn","约翰·麦金","Central Midfield","中前卫","Aston Villa","阿斯顿维拉"),
    p("8","Billy Gilmour","比利·吉尔摩","Central Midfield","中前卫","Napoli","那不勒斯"),
    p("14","Ryan Christie","瑞安·克里斯蒂","Attacking Midfield","攻击中场","Bournemouth","伯恩茅斯"),
    p("17","Lewis Ferguson","刘易斯·弗格森","Central Midfield","中前卫","Bologna","博洛尼亚"),
    p("19","Ben Doak","本·多克","Winger","边锋","Bournemouth","伯恩茅斯"),
    p("9","Ché Adams","切·亚当斯","Centre-Forward","中锋","Torino","都灵"),
    p("10","Lawrence Shankland","劳伦斯·尚克兰","Centre-Forward","中锋","Hearts","哈茨"),
    p("11","Lyndon Dykes","林登·戴克斯","Centre-Forward","中锋","Charlton","查尔顿"),
    p("18","George Hirst","乔治·赫斯特","Forward","前锋","Ipswich","伊普斯维奇"),
    p("20","Ross Stewart","罗斯·斯图尔特","Forward","前锋","Southampton","南安普顿"),
]}

wiki["Haiti"] = {"coach":"Sébastien Migné","players":[
    p("1","Johny Placide","约翰尼·普拉西德","Goalkeeper","门将","Bastia","巴斯蒂亚"),
    p("12","Alexandre Pierre","亚历山大·皮埃尔","Goalkeeper","门将","Sochaux","索肖"),
    p("2","Carlens Arcus","卡伦斯·阿库斯","Right-Back","右后卫","Angers","昂热"),
    p("3","Martin Expérience","马丁·埃克斯佩里安斯","Defender","后卫","Nancy","南锡"),
    p("4","Ricardo Adé","里卡多·阿代","Centre-Back","中后卫","LDU Quito","LDU基多"),
    p("5","Jean-Kévin Duverne","让-凯文·杜韦恩","Centre-Back","中后卫","Gent","根特"),
    p("6","Duke Lacroix","杜克·拉克鲁瓦","Defender","后卫","Colorado Springs","科罗拉多斯普林斯"),
    p("7","Jean-Ricner Bellegarde","让-里克纳·贝勒加德","Central Midfield","中前卫","Wolves","狼队"),
    p("8","Danley Jean Jacques","丹利·让-雅克","Defensive Midfield","防守中场","Philadelphia Union","费城联合"),
    p("9","Duckens Nazon","杜肯斯·纳宗","Centre-Forward","中锋","Esteghlal","德黑兰独立"),
    p("10","Frantzdy Pierrot","弗朗茨迪·皮埃罗","Centre-Forward","中锋","Çaykur Rizespor","里泽体育"),
    p("11","Derrick Etienne","德里克·艾蒂安","Winger","边锋","Toronto FC","多伦多FC"),
    p("13","Wilson Isidor","威尔逊·伊西多尔","Forward","前锋","Sunderland","桑德兰"),
    p("14","Carl Fred Sainté","卡尔·弗雷德·桑特","Midfielder","中场","El Paso Locomotive","埃尔帕索火车头"),
    p("15","Don Deedson Louicius","唐·迪德森·路易修斯","Forward","前锋","FC Dallas","达拉斯FC"),
    p("16","Josué Casimir","若苏埃·卡西米尔","Forward","前锋","Auxerre","欧塞尔"),
    p("17","Ruben Providence","鲁本·普罗维登斯","Winger","边锋","Almere","阿尔梅勒"),
    p("18","Yassin Fortuné","亚辛·福图内","Forward","前锋","Vizela","维泽拉"),
    p("19","Lenny Joseph","莱尼·约瑟夫","Forward","前锋","Ferencváros","费伦茨瓦罗斯"),
    p("20","Leverton Pierre","莱弗顿·皮埃尔","Midfielder","中场","Vizela","维泽拉"),
]}

# Save progress
json.dump(wiki, open('wiki_squads.json','w',encoding='utf-8'), ensure_ascii=False, indent=2)
print(f'Part 1 done: {len(wiki)} teams, {sum(len(t["players"]) for t in wiki.values())} players')
