#!/usr/bin/env python3
"""Part 3: Final 18 teams to complete all 48"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def P(num, name, cn, pos, poscn, club, clubcn=""):
    return {"number":num,"name":name,"name_cn":cn,"position":pos,"position_cn":poscn,"club":club,"club_cn":clubcn or club}

wiki = json.load(open('wiki_squads.json', encoding='utf-8'))

# ===== GROUP H (Spain already done) =====
wiki["Uruguay"] = {"coach":"Marcelo Bielsa","players":[
    P("1","Fernando Muslera","费尔南多·穆斯莱拉","Goalkeeper","门将","Galatasaray","加拉塔萨雷"),
    P("12","Sergio Rochet","塞尔吉奥·罗切特","Goalkeeper","门将","Internacional","巴西国际"),
    P("23","Santiago Mele","圣地亚哥·梅莱","Goalkeeper","门将","Junior","巴兰基亚青年"),
    P("2","Ronald Araújo","罗纳德·阿劳霍","Centre-Back","中后卫","Barcelona","巴塞罗那"),
    P("3","José María Giménez","何塞·希门尼斯","Centre-Back","中后卫","Atlético Madrid","马德里竞技"),
    P("4","Santiago Bueno","圣地亚哥·布埃诺","Centre-Back","中后卫","Wolves","狼队"),
    P("5","Mathías Olivera","马蒂亚斯·奥利维拉","Left-Back","左后卫","Napoli","那不勒斯"),
    P("13","Sebastián Cáceres","塞巴斯蒂安·卡塞雷斯","Centre-Back","中后卫","Club América","美洲队"),
    P("6","Federico Valverde","费德里科·巴尔韦德","Central Midfield","中前卫","Real Madrid","皇家马德里"),
    P("7","Rodrigo Bentancur","罗德里戈·本坦库尔","Central Midfield","中前卫","Tottenham Hotspur","托特纳姆热刺"),
    P("8","Manuel Ugarte","曼努埃尔·乌加特","Defensive Midfield","防守中场","Paris SG","巴黎圣日耳曼"),
    P("14","Giorgian De Arrascaeta","乔治安·德阿拉斯卡埃塔","Attacking Midfield","攻击中场","Flamengo","弗拉门戈"),
    P("15","Nicolás De La Cruz","尼古拉斯·德拉克鲁斯","Central Midfield","中前卫","River Plate","河床"),
    P("16","Rodrigo Zalazar","罗德里戈·萨拉查","Midfielder","中场","Braga","布拉加"),
    P("9","Darwin Núñez","达尔文·努涅斯","Centre-Forward","中锋","Liverpool","利物浦"),
    P("10","Federico Viñas","费德里科·比尼亚斯","Forward","前锋","Real Oviedo","皇家奥维耶多"),
    P("11","Maximiliano Araújo","马克西米利亚诺·阿劳霍","Winger","边锋","Toluca","托卢卡"),
    P("17","Facundo Pellistri","法昆多·佩利斯特里","Winger","边锋","Manchester United","曼联"),
    P("18","Brian Rodríguez","布赖恩·罗德里格斯","Winger","边锋","Club América","美洲队"),
    P("19","Rodrigo Aguirre","罗德里戈·阿吉雷","Forward","前锋","América Mineiro","阿美利加明尼路"),
]}

wiki["Saudi Arabia"] = {"coach":"Georgios Donis","players":[
    P("1","Mohammed Al Owais","穆罕默德·奥韦斯","Goalkeeper","门将","Al-Hilal","利雅得新月"),
    P("21","Nawaf Al Aqidi","纳瓦夫·阿基迪","Goalkeeper","门将","Al-Nassr","利雅得胜利"),
    P("22","Ahmed Al Kassar","艾哈迈德·卡萨尔","Goalkeeper","门将","Al-Qadsiah","卡迪西亚"),
    P("2","Abdulelah Al Amri","阿卜杜勒拉·阿姆里","Centre-Back","中后卫","Al-Nassr","利雅得胜利"),
    P("3","Hassan Tambakti","哈桑·坦巴克蒂","Centre-Back","中后卫","Al-Hilal","利雅得新月"),
    P("4","Ali Lajami","阿里·拉贾米","Centre-Back","中后卫","Al-Nassr","利雅得胜利"),
    P("5","Saud Abdulhamid","沙特·阿卜杜勒哈米德","Right-Back","右后卫","Al-Hilal","利雅得新月"),
    P("6","Hassan Kadesh","哈桑·卡代什","Left-Back","左后卫","Al-Ittihad","吉达联合"),
    P("13","Moteb Al Harbi","穆特布·哈尔比","Defender","后卫","Al-Hilal","利雅得新月"),
    P("7","Mohammed Kanno","穆罕默德·坎诺","Central Midfield","中前卫","Al-Hilal","利雅得新月"),
    P("8","Abdullah Al Khaibari","阿卜杜拉·海巴里","Defensive Midfield","防守中场","Al-Nassr","利雅得胜利"),
    P("14","Salem Al Dawsari","萨勒姆·达瓦萨里","Winger","边锋","Al-Hilal","利雅得新月"),
    P("15","Nasser Al Dawsari","纳赛尔·达瓦萨里","Midfielder","中场","Al-Hilal","利雅得新月"),
    P("9","Firas Al Buraikan","菲拉斯·布赖坎","Centre-Forward","中锋","Al-Ahli","吉达国民"),
    P("10","Saleh Al Shehri","萨利赫·谢赫里","Centre-Forward","中锋","Al-Hilal","利雅得新月"),
    P("11","Abdullah Al Hamdan","阿卜杜拉·哈姆丹","Forward","前锋","Al-Hilal","利雅得新月"),
]}

wiki["Cape Verde"] = {"coach":"Bubista","players":[
    P("1","Vozinha","沃齐尼亚","Goalkeeper","门将","CF Estrela","埃斯特雷拉"),
    P("12","Márcio Rosa","马尔西奥·罗萨","Goalkeeper","门将","AVS","AVS"),
    P("2","Stopira","斯托皮拉","Left-Back","左后卫","Boavista","博阿维斯塔"),
    P("3","Roberto Lopes","罗伯托·洛佩斯","Centre-Back","中后卫","Shamrock Rovers","沙姆洛克流浪者"),
    P("4","Logan Costa","洛根·科斯塔","Centre-Back","中后卫","Toulouse","图卢兹"),
    P("5","Steve Furtado","史蒂夫·富尔塔多","Right-Back","右后卫","CSKA 1948","陆军1948"),
    P("6","Jamiro Monteiro","雅米罗·蒙泰罗","Central Midfield","中前卫","San Jose Earthquakes","圣何塞地震"),
    P("7","Ryan Mendes","瑞安·门德斯","Winger","边锋","Al-Nasr","胜利"),
    P("8","Deroy Duarte","德罗伊·杜阿尔特","Midfielder","中场","Fortuna Sittard","锡塔德幸运"),
    P("9","Garry Rodrigues","加里·罗德里格斯","Winger","边锋","Al-Wehda","团结"),
    P("10","Bébé","贝贝","Forward","前锋","Rayo Vallecano","巴列卡诺"),
    P("11","Willy Semedo","威利·塞梅多","Winger","边锋","Al-Fayha","哈萨征服"),
    P("13","João Paulo","若昂·保罗","Midfielder","中场","Feirense","费伦斯"),
    P("14","Hélio Varela","埃利奥·瓦雷拉","Forward","前锋","Portimonense","波尔蒂芒人"),
    P("15","Tiago Almeida","蒂亚戈·阿尔梅达","Defender","后卫","Casa Pia","卡萨皮亚"),
]}

# ===== GROUP I (France already done) =====
wiki["Senegal"] = {"coach":"Pape Thiaw","players":[
    P("16","Édouard Mendy","爱德华·门迪","Goalkeeper","门将","Al-Ahli","吉达国民"),
    P("1","Seny Dieng","塞尼·迪昂","Goalkeeper","门将","Middlesbrough","米德尔斯堡"),
    P("23","Mory Diaw","莫里·迪奥","Goalkeeper","门将","Clermont Foot","克莱蒙"),
    P("2","Kalidou Koulibaly","卡利杜·库利巴利","Centre-Back","中后卫","Al-Hilal","利雅得新月"),
    P("3","Abdou Diallo","阿卜杜·迪亚洛","Centre-Back","中后卫","Al-Arabi","阿拉比"),
    P("4","Moussa Niakhaté","穆萨·尼亚卡特","Centre-Back","中后卫","Nottingham Forest","诺丁汉森林"),
    P("5","Ismail Jakobs","伊斯梅尔·雅各布斯","Left-Back","左后卫","AS Monaco","摩纳哥"),
    P("22","Fodé Ballo-Touré","福德·巴洛-图雷","Left-Back","左后卫","AC Milan","AC米兰"),
    P("6","Idrissa Gueye","伊德里萨·盖耶","Defensive Midfield","防守中场","Everton","埃弗顿"),
    P("7","Pape Matar Sarr","帕普·马塔尔·萨尔","Central Midfield","中前卫","Tottenham Hotspur","托特纳姆热刺"),
    P("8","Lamine Camara","拉明·卡马拉","Central Midfield","中前卫","AS Monaco","摩纳哥"),
    P("15","Pathé Ciss","帕特·西斯","Defensive Midfield","防守中场","Rayo Vallecano","巴列卡诺"),
    P("9","Sadio Mané","萨迪奥·马内","Left Wing","左边锋","Al-Nassr","利雅得胜利"),
    P("10","Ismaïla Sarr","伊斯梅拉·萨尔","Winger","边锋","Marseille","马赛"),
    P("11","Nicolas Jackson","尼古拉·杰克逊","Centre-Forward","中锋","Chelsea","切尔西"),
    P("12","Boulaye Dia","布莱耶·迪亚","Centre-Forward","中锋","Lazio","拉齐奥"),
    P("13","Iliman Ndiaye","伊利曼·恩迪亚耶","Attacking Midfield","攻击中场","Everton","埃弗顿"),
    P("14","Habib Diallo","哈比卜·迪亚洛","Centre-Forward","中锋","Al-Shabab","利雅得青年"),
]}

wiki["Iraq"] = {"coach":"Jesús Casas","players":[
    P("1","Jalal Hassan","贾拉勒·哈桑","Goalkeeper","门将","Al-Zawraa","扎瓦拉"),
    P("12","Ahmed Basil","艾哈迈德·巴希尔","Goalkeeper","门将","Al-Shorta","警察"),
    P("2","Rebin Sulaka","雷宾·苏拉卡","Centre-Back","中后卫","Viborg","维堡"),
    P("3","Zaid Tahseen","扎伊德·塔辛","Defender","后卫","Al-Quwa Al-Jawiya","空军"),
    P("4","Hussein Ali","侯赛因·阿里","Defender","后卫","Heerenveen","海伦芬"),
    P("5","Ali Adnan","阿里·阿德南","Left-Back","左后卫","Al-Najaf","纳杰夫"),
    P("6","Amir Al-Ammari","阿米尔·阿马里","Defensive Midfield","防守中场","Halmstad","哈尔姆斯塔德"),
    P("7","Zidane Iqbal","齐达内·伊克巴尔","Central Midfield","中前卫","FC Utrecht","乌德勒支"),
    P("8","Ibrahim Bayesh","易卜拉欣·巴耶什","Midfielder","中场","Al-Quwa Al-Jawiya","空军"),
    P("9","Aymen Hussein","艾曼·侯赛因","Centre-Forward","中锋","Al-Jazira","半岛"),
    P("10","Ali Al-Hamadi","阿里·哈马迪","Forward","前锋","Ipswich Town","伊普斯维奇"),
    P("11","Mohanad Ali","穆哈纳德·阿里","Forward","前锋","Al-Shorta","警察"),
    P("13","Osama Rashid","奥萨马·拉希德","Midfielder","中场","Vizela","维泽拉"),
    P("14","Mohammed Qasim","穆罕默德·卡西姆","Winger","边锋","Al-Shorta","警察"),
]}

wiki["Norway"] = {"coach":"Ståle Solbakken","players":[
    P("1","Ørjan Nyland","厄尔扬·尼兰","Goalkeeper","门将","Sevilla","塞维利亚"),
    P("12","Egil Selvik","埃吉尔·塞尔维克","Goalkeeper","门将","Haugesund","海于格松"),
    P("23","Sander Tangvik","桑德·唐维克","Goalkeeper","门将","Rosenborg","罗森博格"),
    P("2","Julian Ryerson","朱利安·瑞尔森","Right-Back","右后卫","Borussia Dortmund","多特蒙德"),
    P("3","Kristoffer Ajer","克里斯托弗·阿耶尔","Centre-Back","中后卫","Brentford","布伦特福德"),
    P("4","Leo Østigård","莱奥·厄斯蒂高","Centre-Back","中后卫","Rennes","雷恩"),
    P("5","David Møller Wolfe","大卫·穆勒·沃尔夫","Left-Back","左后卫","AZ Alkmaar","阿尔克马尔"),
    P("13","Marcus Pedersen","马库斯·佩德森","Right-Back","右后卫","Sassuolo","萨索洛"),
    P("14","Torbjørn Heggem","托尔比约恩·赫格姆","Defender","后卫","West Brom","西布朗"),
    P("6","Sander Berge","桑德·贝格","Defensive Midfield","防守中场","Fulham","富勒姆"),
    P("7","Martin Ødegaard","马丁·厄德高","Attacking Midfield","攻击中场","Arsenal","阿森纳"),
    P("8","Kristian Thorstvedt","克里斯蒂安·托斯特维特","Central Midfield","中前卫","Sassuolo","萨索洛"),
    P("15","Patrick Berg","帕特里克·贝格","Central Midfield","中前卫","Bodø/Glimt","博德闪耀"),
    P("16","Oscar Bobb","奥斯卡·鲍勃","Winger","边锋","Manchester City","曼城"),
    P("17","Antonio Nusa","安东尼奥·努萨","Winger","边锋","Club Brugge","布鲁日"),
    P("18","Andreas Schjelderup","安德烈亚斯·谢尔德鲁普","Winger","边锋","Benfica","本菲卡"),
    P("9","Erling Haaland","埃尔林·哈兰德","Centre-Forward","中锋","Manchester City","曼城"),
    P("10","Alexander Sørloth","亚历山大·瑟洛特","Centre-Forward","中锋","Atlético Madrid","马德里竞技"),
    P("11","Jørgen Strand Larsen","约尔根·斯特兰德·拉森","Forward","前锋","Wolves","狼队"),
    P("19","Jens Petter Hauge","延斯·彼得·海于格","Winger","边锋","Bodø/Glimt","博德闪耀"),
    P("20","Fredrik Aursnes","弗雷德里克·奥尔斯内斯","Central Midfield","中前卫","Benfica","本菲卡"),
    P("21","Morten Thorsby","莫滕·托尔斯比","Midfielder","中场","Genoa","热那亚"),
    P("22","Thelo Aasgaard","特洛·奥斯高","Midfielder","中场","Wigan Athletic","维冈竞技"),
]}

# ===== GROUP J (Argentina already done) =====
wiki["Algeria"] = {"coach":"Vladimir Petković","players":[
    P("1","Anthony Mandrea","安东尼·曼德雷亚","Goalkeeper","门将","Caen","卡昂"),
    P("16","Alexandre Oukidja","亚历山大·乌基贾","Goalkeeper","门将","Metz","梅斯"),
    P("23","Raïs M'Bolhi","拉伊斯·姆博利","Goalkeeper","门将","CR Belouizdad","贝卢兹达德"),
    P("2","Aïssa Mandi","艾萨·曼迪","Centre-Back","中后卫","Lille","里尔"),
    P("3","Ramy Bensebaini","拉米·本塞拜尼","Left-Back","左后卫","Borussia Dortmund","多特蒙德"),
    P("4","Mohamed Amine Tougai","穆罕默德·图加伊","Centre-Back","中后卫","Espérance","突尼斯希望"),
    P("5","Rayan Aït-Nouri","拉扬·艾特-努里","Left-Back","左后卫","Wolves","狼队"),
    P("6","Ismaël Bennacer","伊斯梅尔·本纳赛尔","Defensive Midfield","防守中场","Marseille","马赛"),
    P("7","Riyad Mahrez","里亚德·马赫雷斯","Right Winger","右边锋","Al-Ahli","吉达国民"),
    P("8","Houssem Aouar","侯塞姆·阿瓦尔","Central Midfield","中前卫","Al-Ittihad","吉达联合"),
    P("9","Baghdad Bounedjah","巴格达·布内贾","Centre-Forward","中锋","Al-Sadd","萨德"),
    P("10","Saïd Benrahma","赛义德·本拉赫马","Winger","边锋","Lyon","里昂"),
    P("11","Anis Hadj Moussa","阿尼斯·哈吉·穆萨","Winger","边锋","Feyenoord","费耶诺德"),
    P("12","Mohamed Amoura","穆罕默德·阿穆拉","Forward","前锋","Wolfsburg","沃尔夫斯堡"),
    P("13","Fares Chaïbi","法雷斯·沙伊比","Attacking Midfield","攻击中场","Eintracht Frankfurt","法兰克福"),
]}

wiki["Austria"] = {"coach":"Ralf Rangnick","players":[
    P("1","Heinz Lindner","海因茨·林德纳","Goalkeeper","门将","Sion","锡永"),
    P("12","Niklas Hedl","尼克拉斯·赫德尔","Goalkeeper","门将","Rapid Wien","维也纳快速"),
    P("13","Patrick Pentz","帕特里克·彭茨","Goalkeeper","门将","Brøndby","布隆德比"),
    P("2","Stefan Posch","斯特凡·波施","Right-Back","右后卫","Bologna","博洛尼亚"),
    P("3","Kevin Danso","凯文·丹索","Centre-Back","中后卫","Lens","朗斯"),
    P("4","Philipp Lienhart","菲利普·林哈特","Centre-Back","中后卫","Freiburg","弗赖堡"),
    P("5","Maximilian Wöber","马克西米利安·韦伯","Centre-Back","中后卫","Leeds United","利兹联"),
    P("6","Nicolas Seiwald","尼古拉斯·赛瓦尔德","Central Midfield","中前卫","RB Leipzig","RB莱比锡"),
    P("7","Konrad Laimer","康拉德·莱默","Central Midfield","中前卫","Bayern Munich","拜仁慕尼黑"),
    P("8","Christoph Baumgartner","克里斯托夫·鲍姆加特纳","Attacking Midfield","攻击中场","RB Leipzig","RB莱比锡"),
    P("9","Marcel Sabitzer","马塞尔·萨比策","Central Midfield","中前卫","Borussia Dortmund","多特蒙德"),
    P("10","Marko Arnautović","马尔科·阿尔瑙托维奇","Centre-Forward","中锋","Inter Milan","国际米兰"),
    P("11","Michael Gregoritsch","米夏埃尔·格雷戈里奇","Forward","前锋","Freiburg","弗赖堡"),
    P("14","Junior Adamu","朱尼奥尔·阿达姆","Forward","前锋","Freiburg","弗赖堡"),
    P("15","Romano Schmid","罗马诺·施密德","Attacking Midfield","攻击中场","Werder Bremen","云达不莱梅"),
]}

wiki["Jordan"] = {"coach":"Hussein Ammouta","players":[
    P("1","Yazeed Abu Laila","亚齐德·阿布莱拉","Goalkeeper","门将","Al-Faisaly","费萨里"),
    P("12","Abdallah Al-Fakhouri","阿卜杜拉·法胡里","Goalkeeper","门将","Al-Wehdat","团结"),
    P("2","Abdallah Nasib","阿卜杜拉·纳西布","Centre-Back","中后卫","Al-Hussein","侯赛因"),
    P("3","Yazan Al-Arab","亚赞·阿拉伯","Centre-Back","中后卫","Al-Wehdat","团结"),
    P("4","Mohammad Abu Hashish","穆罕默德·阿布·哈希什","Defender","后卫","Al-Faisaly","费萨里"),
    P("5","Ehsan Haddad","埃赫桑·哈达德","Right-Back","右后卫","Al-Faisaly","费萨里"),
    P("6","Nizar Al-Rashdan","尼扎尔·拉什丹","Defensive Midfield","防守中场","Al-Faisaly","费萨里"),
    P("7","Musa Al-Taamari","穆萨·塔马里","Winger","边锋","Montpellier","蒙彼利埃"),
    P("8","Rajaei Ayed","拉贾伊·阿耶德","Midfielder","中场","Al-Hussein","侯赛因"),
    P("9","Ali Olwan","阿里·奥尔万","Forward","前锋","Al-Shamal","沙马尔"),
    P("10","Yazan Al-Naimat","亚赞·奈马特","Centre-Forward","中锋","Al-Arabi","阿拉比"),
    P("11","Mohammad Al-Mardi","穆罕默德·马尔迪","Midfielder","中场","Al-Hussein","侯赛因"),
    P("13","Ibrahim Sadeh","易卜拉欣·萨德","Midfielder","中场","Al-Hussein","侯赛因"),
    P("14","Mahmoud Al-Mardi","马哈茂德·马尔迪","Winger","边锋","Al-Hussein","侯赛因"),
]}

# ===== GROUP K =====
wiki["Portugal"] = {"coach":"Roberto Martínez","players":[
    P("1","Diogo Costa","迪奥戈·科斯塔","Goalkeeper","门将","FC Porto","波尔图"),
    P("12","José Sá","若泽·萨","Goalkeeper","门将","Wolves","狼队"),
    P("22","Rui Silva","鲁伊·席尔瓦","Goalkeeper","门将","Sporting CP","葡萄牙体育"),
    P("2","Nélson Semedo","塞梅多","Right-Back","右后卫","Fenerbahçe","费内巴切"),
    P("3","Rúben Dias","鲁本·迪亚斯","Centre-Back","中后卫","Manchester City","曼城"),
    P("4","Tomás Araújo","托马斯·阿劳若","Centre-Back","中后卫","Benfica","本菲卡"),
    P("5","Diogo Dalot","达洛特","Right-Back","右后卫","Manchester United","曼联"),
    P("20","João Cancelo","坎塞洛","Left-Back","左后卫","Barcelona","巴塞罗那"),
    P("25","Nuno Mendes","努诺·门德斯","Left-Back","左后卫","Paris SG","巴黎圣日耳曼"),
    P("14","Gonçalo Inácio","伊纳西奥","Centre-Back","中后卫","Sporting CP","葡萄牙体育"),
    P("6","João Palhinha","帕利尼亚","Defensive Midfield","防守中场","Bayern Munich","拜仁慕尼黑"),
    P("8","Bruno Fernandes","布鲁诺·费尔南德斯","Attacking Midfield","攻击中场","Manchester United","曼联"),
    P("10","Bernardo Silva","贝尔纳多·席尔瓦","Right Winger","右边锋","Manchester City","曼城"),
    P("15","João Neves","若昂·内维斯","Central Midfield","中前卫","Paris SG","巴黎圣日耳曼"),
    P("23","Vitinha","维蒂尼亚","Central Midfield","中前卫","Paris SG","巴黎圣日耳曼"),
    P("21","Rúben Neves","鲁本·内维斯","Defensive Midfield","防守中场","Al-Hilal","利雅得新月"),
    P("7","Cristiano Ronaldo","克里斯蒂亚诺·罗纳尔多","Centre-Forward","中锋","Al-Nassr","利雅得胜利"),
    P("9","Gonçalo Ramos","贡萨洛·拉莫斯","Centre-Forward","中锋","Paris SG","巴黎圣日耳曼"),
    P("11","João Félix","若昂·菲利克斯","Forward","前锋","Al-Nassr","利雅得胜利"),
    P("17","Rafael Leão","拉斐尔·莱奥","Left Wing","左边锋","AC Milan","AC米兰"),
    P("18","Pedro Neto","佩德罗·内托","Winger","边锋","Chelsea","切尔西"),
    P("16","Francisco Trincão","特林康","Winger","边锋","Sporting CP","葡萄牙体育"),
    P("19","Gonçalo Guedes","贡萨洛·格德斯","Forward","前锋","Real Sociedad","皇家社会"),
    P("26","Francisco Conceição","弗朗西斯科·孔塞桑","Winger","边锋","Juventus","尤文图斯"),
    P("24","Samu Costa","萨穆·科斯塔","Midfielder","中场","Mallorca","马略卡"),
    P("13","Renato Veiga","雷纳托·韦加","Defender","后卫","Villarreal","比利亚雷亚尔"),
]}

wiki["DR Congo"] = {"coach":"Sébastien Desabre","players":[
    P("1","Lionel M'Pasi","利昂内尔·姆帕西","Goalkeeper","门将","Rodez","罗德兹"),
    P("16","Dimitry Bertaud","迪米特里·贝尔托","Goalkeeper","门将","Montpellier","蒙彼利埃"),
    P("2","Chancel Mbemba","尚塞尔·姆本巴","Centre-Back","中后卫","Marseille","马赛"),
    P("3","Axel Tuanzebe","阿克塞尔·图安泽贝","Centre-Back","中后卫","Ipswich Town","伊普斯维奇"),
    P("4","Brian Bayeye","布赖恩·巴耶耶","Defender","后卫","Torino","都灵"),
    P("5","Arthur Masuaku","阿蒂尔·马苏亚库","Left-Back","左后卫","Beşiktaş","贝西克塔什"),
    P("6","Edo Kayembe","埃多·卡延贝","Defensive Midfield","防守中场","Watford","沃特福德"),
    P("7","Samuel Moutoussamy","萨穆埃尔·穆图萨米","Central Midfield","中前卫","Nantes","南特"),
    P("8","Gaël Kakuta","加埃勒·卡库塔","Attacking Midfield","攻击中场","Amiens","亚眠"),
    P("9","Yoane Wissa","约安·维萨","Forward","前锋","Brentford","布伦特福德"),
    P("10","Théo Bongonda","特奥·邦贡达","Winger","边锋","Spartak Moscow","莫斯科斯巴达"),
    P("11","Meschack Elia","梅沙克·埃利亚","Forward","前锋","Young Boys Bern","伯尔尼年轻人"),
    P("12","Cédric Bakambu","塞德里克·巴坎布","Centre-Forward","中锋","Real Betis","皇家贝蒂斯"),
    P("13","Noah Sadiki","诺亚·萨迪基","Midfielder","中场","Union St-Gilloise","圣吉罗斯联合"),
    P("14","Simon Banza","西蒙·班扎","Centre-Forward","中锋","Braga","布拉加"),
]}

wiki["Uzbekistan"] = {"coach":"Timur Kapadze","players":[
    P("1","Utkir Yusupov","乌特基尔·尤苏波夫","Goalkeeper","门将","Navbahor","纳夫巴霍尔"),
    P("12","Botirali Ergashev","博蒂拉利·埃尔加舍夫","Goalkeeper","门将","AGMK","阿尔马雷克"),
    P("2","Umar Eshmuradov","乌马尔·埃什穆罗多夫","Centre-Back","中后卫","Nasaf","纳萨夫"),
    P("3","Rustam Ashurmatov","鲁斯塔姆·阿舒尔马托夫","Centre-Back","中后卫","Rubin Kazan","喀山红宝石"),
    P("4","Abduqodir Khusanov","阿卜杜科迪尔·胡萨诺夫","Centre-Back","中后卫","Manchester City","曼城"),
    P("5","Farrukh Sayfiev","法鲁赫·赛菲耶夫","Left-Back","左后卫","Pakhtakor","棉农"),
    P("6","Odiljon Xamrobekov","奥迪尔忠·哈姆罗别科夫","Defensive Midfield","防守中场","Pakhtakor","棉农"),
    P("7","Oston Urunov","奥斯通·乌鲁诺夫","Winger","边锋","Persepolis","波斯波利斯"),
    P("8","Jaloliddin Masharipov","贾洛利丁·马沙里波夫","Attacking Midfield","攻击中场","Al-Nassr","利雅得胜利"),
    P("9","Eldor Shomurodov","埃尔多尔·绍穆罗多夫","Centre-Forward","中锋","Cagliari","卡利亚里"),
    P("10","Khojimat Erkinov","霍吉马特·埃尔基诺夫","Winger","边锋","Al-Wahda","统一"),
    P("11","Abbosbek Fayzullayev","阿博斯别克·法伊祖拉耶夫","Attacking Midfield","攻击中场","CSKA Moscow","莫斯科中央陆军"),
    P("13","Bobur Abdukhalikov","博布尔·阿卜杜哈利科夫","Forward","前锋","Nasaf","纳萨夫"),
    P("14","Sherzod Nasrulloyev","谢尔佐德·纳斯鲁拉耶夫","Defender","后卫","Nasaf","纳萨夫"),
]}

wiki["Colombia"] = {"coach":"Néstor Lorenzo","players":[
    P("1","Camilo Vargas","卡米洛·巴尔加斯","Goalkeeper","门将","Atlas","阿特拉斯"),
    P("12","Kevin Mier","凯文·米耶尔","Goalkeeper","门将","Cruz Azul","蓝十字"),
    P("23","Álvaro Montero","阿尔瓦罗·蒙特罗","Goalkeeper","门将","Millonarios","百万富翁"),
    P("2","Daniel Muñoz","丹尼尔·穆尼奥斯","Right-Back","右后卫","Crystal Palace","水晶宫"),
    P("3","Jhon Lucumí","约翰·卢库米","Centre-Back","中后卫","Bologna","博洛尼亚"),
    P("4","Carlos Cuesta","卡洛斯·奎斯塔","Centre-Back","中后卫","Genk","亨克"),
    P("5","Davinson Sánchez","达文松·桑切斯","Centre-Back","中后卫","Galatasaray","加拉塔萨雷"),
    P("6","Deiver Machado","代韦尔·马查多","Left-Back","左后卫","Lens","朗斯"),
    P("7","Jhon Arias","约翰·阿里亚斯","Winger","边锋","Fluminense","弗鲁米嫩塞"),
    P("8","Jefferson Lerma","杰弗森·莱尔马","Defensive Midfield","防守中场","Crystal Palace","水晶宫"),
    P("10","James Rodríguez","哈梅斯·罗德里格斯","Attacking Midfield","攻击中场","São Paulo","圣保罗"),
    P("14","Jhon Durán","约翰·杜兰","Centre-Forward","中锋","Aston Villa","阿斯顿维拉"),
    P("9","Luis Díaz","路易斯·迪亚斯","Left Wing","左边锋","Liverpool","利物浦"),
    P("11","Rafael Santos Borré","拉斐尔·桑托斯·博雷","Forward","前锋","Internacional","巴西国际"),
    P("15","Jhon Córdoba","约翰·科尔多瓦","Centre-Forward","中锋","Krasnodar","克拉斯诺达尔"),
]}

# ===== GROUP L =====
wiki["England"] = {"coach":"Thomas Tuchel","players":[
    P("1","Jordan Pickford","乔丹·皮克福德","Goalkeeper","门将","Everton","埃弗顿"),
    P("13","Dean Henderson","迪恩·亨德森","Goalkeeper","门将","Crystal Palace","水晶宫"),
    P("23","James Trafford","詹姆斯·特拉福德","Goalkeeper","门将","Manchester City","曼城"),
    P("2","Ezri Konsa","埃兹里·孔萨","Right-Back","右后卫","Aston Villa","阿斯顿维拉"),
    P("3","Nico O'Reilly","尼科·奥赖利","Defender","后卫","Manchester City","曼城"),
    P("5","John Stones","约翰·斯通斯","Centre-Back","中后卫","Manchester City","曼城"),
    P("6","Marc Guéhi","马克·格伊","Centre-Back","中后卫","Manchester City","曼城"),
    P("12","Tino Livramento","蒂诺·利夫拉门托","Right-Back","右后卫","Newcastle United","纽卡斯尔联"),
    P("15","Dan Burn","丹·伯恩","Centre-Back","中后卫","Newcastle United","纽卡斯尔联"),
    P("24","Reece James","里斯·詹姆斯","Right-Back","右后卫","Chelsea","切尔西"),
    P("25","Djed Spence","杰德·斯彭斯","Left-Back","左后卫","Tottenham Hotspur","托特纳姆热刺"),
    P("26","Jarell Quansah","贾雷尔·宽萨","Centre-Back","中后卫","Bayer Leverkusen","勒沃库森"),
    P("4","Declan Rice","德克兰·赖斯","Defensive Midfield","防守中场","Arsenal","阿森纳"),
    P("8","Elliot Anderson","埃利奥特·安德森","Central Midfield","中前卫","Nottingham Forest","诺丁汉森林"),
    P("10","Jude Bellingham","裘德·贝林厄姆","Attacking Midfield","攻击中场","Real Madrid","皇家马德里"),
    P("16","Kobbie Mainoo","科比·梅努","Central Midfield","中前卫","Manchester United","曼联"),
    P("17","Morgan Rogers","摩根·罗杰斯","Attacking Midfield","攻击中场","Aston Villa","阿斯顿维拉"),
    P("7","Bukayo Saka","布卡约·萨卡","Right Winger","右边锋","Arsenal","阿森纳"),
    P("9","Harry Kane","哈里·凯恩","Centre-Forward","中锋","Bayern Munich","拜仁慕尼黑"),
    P("11","Marcus Rashford","马库斯·拉什福德","Left Wing","左边锋","Barcelona","巴塞罗那"),
    P("18","Anthony Gordon","安东尼·戈登","Winger","边锋","Newcastle United","纽卡斯尔联"),
    P("19","Ollie Watkins","奥利·沃特金斯","Centre-Forward","中锋","Aston Villa","阿斯顿维拉"),
    P("20","Noni Madueke","诺尼·马杜埃凯","Winger","边锋","Arsenal","阿森纳"),
    P("22","Ivan Toney","伊万·托尼","Centre-Forward","中锋","Al-Ahli","吉达国民"),
    P("14","Jordan Henderson","乔丹·亨德森","Central Midfield","中前卫","Brentford","布伦特福德"),
    P("21","Eberechi Eze","埃贝雷奇·埃泽","Attacking Midfield","攻击中场","Arsenal","阿森纳"),
]}

wiki["Croatia"] = {"coach":"Zlatko Dalić","players":[
    P("1","Dominik Livaković","多米尼克·利瓦科维奇","Goalkeeper","门将","Dinamo Zagreb","萨格勒布迪纳摩"),
    P("12","Dominik Kotarski","多米尼克·科塔尔斯基","Goalkeeper","门将","Copenhagen","哥本哈根"),
    P("23","Ivor Pandur","伊沃尔·潘杜尔","Goalkeeper","门将","Hull City","赫尔城"),
    P("2","Joško Gvardiol","约什科·格瓦迪奥尔","Centre-Back","中后卫","Manchester City","曼城"),
    P("3","Duje Ćaleta-Car","杜耶·查莱塔-察尔","Centre-Back","中后卫","Real Sociedad","皇家社会"),
    P("4","Josip Šutalo","约西普·舒塔洛","Centre-Back","中后卫","Ajax","阿贾克斯"),
    P("5","Josip Stanišić","约西普·斯塔尼希奇","Right-Back","右后卫","Bayern Munich","拜仁慕尼黑"),
    P("13","Marin Pongračić","马林·蓬格拉契奇","Centre-Back","中后卫","Fiorentina","佛罗伦萨"),
    P("6","Luka Modrić","卢卡·莫德里奇","Central Midfield","中前卫","AC Milan","AC米兰"),
    P("7","Mateo Kovačić","马特奥·科瓦契奇","Central Midfield","中前卫","Manchester City","曼城"),
    P("8","Mario Pašalić","马里奥·帕沙利奇","Attacking Midfield","攻击中场","Atalanta","亚特兰大"),
    P("10","Nikola Vlašić","尼古拉·弗拉希奇","Attacking Midfield","攻击中场","Torino","都灵"),
    P("14","Luka Sučić","卢卡·苏契奇","Central Midfield","中前卫","Real Sociedad","皇家社会"),
    P("15","Martin Baturina","马丁·巴图里纳","Attacking Midfield","攻击中场","Como","科莫"),
    P("9","Ivan Perišić","伊万·佩里希奇","Winger","边锋","PSV Eindhoven","PSV埃因霍温"),
    P("11","Andrej Kramarić","安德烈·克拉马里奇","Forward","前锋","Hoffenheim","霍芬海姆"),
    P("16","Ante Budimir","安特·布迪米尔","Centre-Forward","中锋","Osasuna","奥萨苏纳"),
    P("17","Petar Musa","佩塔尔·穆萨","Centre-Forward","中锋","FC Dallas","达拉斯FC"),
    P("18","Igor Matanović","伊戈尔·马塔诺维奇","Forward","前锋","Freiburg","弗赖堡"),
    P("19","Marco Pašalić","马尔科·帕沙利奇","Forward","前锋","Orlando City","奥兰多城"),
    P("20","Petar Sučić","佩塔尔·苏契奇","Midfielder","中场","Inter Milan","国际米兰"),
    P("21","Nikola Moro","尼古拉·莫罗","Midfielder","中场","Bologna","博洛尼亚"),
]}

wiki["Ghana"] = {"coach":"Carlos Queiroz","players":[
    P("1","Benjamin Asare","本杰明·阿萨雷","Goalkeeper","门将","Accra Hearts of Oak","橡树之心"),
    P("12","Lawrence Ati-Zigi","劳伦斯·阿蒂-齐吉","Goalkeeper","门将","St. Gallen","圣加仑"),
    P("16","Joseph Anang","约瑟夫·阿南","Goalkeeper","门将","St. Patrick's Athletic","圣帕特里克竞技"),
    P("2","Baba Abdul Rahman","巴巴·阿卜杜勒·拉赫曼","Left-Back","左后卫","PAOK","塞萨洛尼基"),
    P("3","Gideon Mensah","吉迪恩·门萨","Left-Back","左后卫","Auxerre","欧塞尔"),
    P("4","Alidu Seidu","阿利杜·塞杜","Right-Back","右后卫","Rennes","雷恩"),
    P("5","Abdul Mumin","阿卜杜勒·穆明","Centre-Back","中后卫","Rayo Vallecano","巴列卡诺"),
    P("14","Jerome Opoku","杰罗姆·奥波库","Centre-Back","中后卫","Istanbul Başakşehir","伊斯坦布尔"),
    P("6","Thomas Partey","托马斯·帕尔特伊","Defensive Midfield","防守中场","Villarreal","比利亚雷亚尔"),
    P("7","Kamaldeen Sulemana","卡马尔丁·苏莱马纳","Winger","边锋","Atalanta","亚特兰大"),
    P("8","Elisha Owusu","以利沙·奥乌苏","Central Midfield","中前卫","Auxerre","欧塞尔"),
    P("15","Abdul Fatawu Issahaku","阿卜杜勒·法塔乌","Winger","边锋","Leicester City","莱斯特城"),
    P("9","Antoine Semenyo","安托万·塞梅尼奥","Forward","前锋","Manchester City","曼城"),
    P("10","Jordan Ayew","乔丹·阿尤","Forward","前锋","Leicester City","莱斯特城"),
    P("11","Iñaki Williams","伊尼亚基·威廉姆斯","Right Winger","右边锋","Athletic Bilbao","毕尔巴鄂竞技"),
    P("13","Ernest Nuamah","欧内斯特·努瓦马","Winger","边锋","Lyon","里昂"),
    P("17","Brandon Thomas-Asante","布兰登·托马斯-阿桑特","Forward","前锋","Coventry City","考文垂"),
    P("18","Prince Kwabena Adu","普林斯·阿杜","Forward","前锋","Viktoria Plzeň","比尔森胜利"),
]}

wiki["Panama"] = {"coach":"Thomas Christiansen","players":[
    P("1","Luis Mejía","路易斯·梅希亚","Goalkeeper","门将","Nacional","乌拉圭民族"),
    P("12","Orlando Mosquera","奥兰多·莫斯克拉","Goalkeeper","门将","Al-Fateh","哈萨征服"),
    P("22","Miguel Pérez","米格尔·佩雷斯","Goalkeeper","门将","Sporting San Miguelito","圣米格利托"),
    P("2","Michael Amir Murillo","迈克尔·穆里略","Right-Back","右后卫","Marseille","马赛"),
    P("3","Fidel Escobar","菲德尔·埃斯科瓦尔","Centre-Back","中后卫","Al-Qadsiah","卡迪西亚"),
    P("4","Andrés Andrade","安德烈斯·安德拉德","Centre-Back","中后卫","LASK","林茨"),
    P("5","Edgardo Fariña","埃德加多·法里尼亚","Centre-Back","中后卫","CSKA Moscow","莫斯科中央陆军"),
    P("13","Roderick Miller","罗德里克·米勒","Centre-Back","中后卫","Turan Tovuz","图兰托武兹"),
    P("6","Adalberto Carrasquilla","阿达尔韦托·卡拉斯基亚","Central Midfield","中前卫","Houston Dynamo","休斯顿迪纳摩"),
    P("7","Édgar Bárcenas","埃德加·巴尔塞纳斯","Winger","边锋","Mazatlán","马萨特兰"),
    P("8","Cristian Martínez","克里斯蒂安·马丁内斯","Midfielder","中场","Al-Jandal","詹达尔"),
    P("9","José Fajardo","何塞·法哈多","Forward","前锋","Universidad Católica","天主教大学"),
    P("10","Ismael Díaz","伊斯梅尔·迪亚斯","Forward","前锋","Universidad Católica","天主教大学"),
    P("11","Cecilio Waterman","塞西利奥·沃特曼","Forward","前锋","Coquimbo Unido","科金博联合"),
    P("14","Aníbal Godoy","阿尼瓦尔·戈多伊","Defensive Midfield","防守中场","Nashville SC","纳什维尔SC"),
]}

# Final save
json.dump(wiki, open('wiki_squads.json','w',encoding='utf-8'), ensure_ascii=False, indent=2)
total = sum(len(t['players']) for t in wiki.values())
cn = sum(1 for t in wiki.values() for p in t['players'] if p.get('name_cn'))
print(f'ALL DONE: {len(wiki)}/48 teams, {total} players, {cn} CN names ({100*cn//total}%)')
